(() => {
  const CONFIG={
    marek:{name:'Marek',armor:{id:'gambeson',name:'Gambeson Armor'},weapons:{
      'shortstaff':{name:'Shortstaff',slot:'primary',burden:1,meta:'Instinct · Close · d8+1 magic',actions:['Shortstaff']},
      'round-shield':{name:'Round Shield',slot:'secondary',burden:1,meta:'Strength · Melee · d4 physical · Protective +1 Armor',actions:['Round Shield']}
    },gear:['Torch','50 ft Rope','Basic Supplies','Small Bag of Rocks and Bones'],consumables:{'minor-stamina':{name:'Minor Stamina Potion',effect:'Clear 1d4 Stress',kind:'stress'}}},
    velmira:{name:'Velmira',armor:{id:'leather-armor',name:'Leather Armor'},weapons:{
      'greatstaff':{name:'Greatstaff',slot:'primary',burden:2,meta:'Knowledge · Very Far · d6 magic · Powerful',actions:['Greatstaff']},
      'whip':{name:'Whip',slot:'secondary',burden:1,meta:'Presence · Very Close · d6 physical · Startling',actions:['Whip','Startling']}
    },gear:['Nomadic Pack'],consumables:{}},
    odie:{name:'Odie',armor:{id:'gambeson',name:'Gambeson Armor'},weapons:{
      'spear':{name:'Spear',slot:'primary',burden:2,meta:'Finesse · Very Close · d8+3 physical',actions:['Spear']},
      'small-dagger':{name:'Small Dagger',slot:'secondary',burden:1,meta:'Finesse · Melee · d8 physical · Paired',actions:['Small Dagger']}
    },gear:['Torch','50 ft Rope','Basic Supplies','Grappling Hook','Salvage-built Prosthetic','Oldwork Finger'],consumables:{'minor-health':{name:'Minor Health Potion',effect:'Clear 1d4 HP',kind:'hp'}}}
  };
  const PREFIX='greywake:equipment-state:v1:';
  let activeKey=null,state=null,observer=null,lastConsumableResult='';
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  const die=sides=>{if(window.crypto?.getRandomValues){const b=new Uint32Array(1);window.crypto.getRandomValues(b);return(b[0]%sides)+1;}return Math.floor(Math.random()*sides)+1;};
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return CONFIG[k]?k:null;}
  function cfg(){return CONFIG[activeKey]||null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function resourceAPI(){return activeKey==='marek'?window.GreywakeResources:window.GreywakeCompanion;}
  function resources(){return resourceAPI()?.getState?.()||null;}
  function weapon(id){return cfg()?.weapons[id]||null;}
  function base(k){if(k==='marek')return{activePrimary:'shortstaff',activeSecondary:'round-shield',activeArmor:'gambeson',inventoryWeapons:[],consumables:{'minor-stamina':1}};if(k==='velmira')return{activePrimary:'greatstaff',activeSecondary:null,activeArmor:'leather-armor',inventoryWeapons:['whip'],consumables:{}};return{activePrimary:'spear',activeSecondary:null,activeArmor:'gambeson',inventoryWeapons:['small-dagger'],consumables:{'minor-health':1}};}
  function normalise(s){const b=base(activeKey),ids=new Set(Object.keys(cfg().weapons));let primary=ids.has(s?.activePrimary)?s.activePrimary:b.activePrimary,secondary=ids.has(s?.activeSecondary)?s.activeSecondary:null;const p=weapon(primary);if(p?.slot!=='primary')primary=null;const sec=weapon(secondary);if(sec?.slot!=='secondary')secondary=null;if(p?.burden===2)secondary=null;let inv=[...new Set((s?.inventoryWeapons||b.inventoryWeapons).filter(id=>ids.has(id)&&id!==primary&&id!==secondary))];for(const id of ids)if(id!==primary&&id!==secondary&&!inv.includes(id))inv.push(id);const consumables={};for(const id of Object.keys(cfg().consumables))consumables[id]=Math.max(0,Math.min(5,Number(s?.consumables?.[id]??b.consumables[id]??0)||0));return{activePrimary:primary,activeSecondary:secondary,activeArmor:s?.activeArmor||b.activeArmor,inventoryWeapons:inv,consumables};}
  function load(k){activeKey=k;let stored=null;try{stored=JSON.parse(localStorage.getItem(PREFIX+k)||'null');}catch(_){}state=normalise(stored||base(k));save();return state;}
  function save(){try{localStorage.setItem(PREFIX+activeKey,JSON.stringify(state));}catch(_){}}
  function snapshot(){return state?{activePrimary:state.activePrimary||null,activeSecondary:state.activeSecondary||null,activeArmor:state.activeArmor||null,inventoryWeapons:[...state.inventoryWeapons],consumables:{...state.consumables}}:null;}
  function commit(next,reason){state=normalise({...state,...next});save();render();window.dispatchEvent(new CustomEvent('greywake:equipment-state-changed',{detail:{ok:true,key:activeKey,reason,state:snapshot()}}));return{ok:true};}
  function importState(remote){if(!remote)return;state=normalise(remote);save();render();}
  function markStress(reason){const api=resourceAPI(),rs=resources();if(!api||!rs)return{ok:false};if(Number(rs.stress)>=Number(rs.maxStress)){alert(`${cfg().name} has no free Stress slot to switch weapons under pressure.`);return{ok:false};}const r=api.markStress?.(1,{reason,cost:true});return r?.ok===false?{ok:false}:{ok:true};}
  function isRestOpen(){return Boolean(document.getElementById('restDialog')?.open);}

  function equip(id,danger=false){if(isPreview()||!state.inventoryWeapons.includes(id))return;const w=weapon(id);if(!w)return;if(danger&&!isRestOpen()){const paid=markStress(`Switch weapon · ${w.name}`);if(!paid.ok)return;}let primary=state.activePrimary,secondary=state.activeSecondary,inventory=state.inventoryWeapons.filter(x=>x!==id);if(w.slot==='primary'){if(primary)inventory.push(primary);primary=id;if(w.burden===2&&secondary){inventory.push(secondary);secondary=null;}}else{if(secondary)inventory.push(secondary);secondary=id;if(primary&&weapon(primary)?.burden===2){inventory.push(primary);primary=null;}}commit({activePrimary:primary,activeSecondary:secondary,inventoryWeapons:inventory},`Equipped ${w.name}${danger&&!isRestOpen()?' under pressure':''}`);closeDialog();}
  function openEquip(id){if(isPreview())return;const w=weapon(id);if(!w)return;if(isRestOpen()){equip(id,false);return;}const d=ensureDialog();d.innerHTML=`<div class="equip-dialog-shell"><div class="equip-dialog-head"><div><span>SWITCH WEAPON</span><h2>Equip ${esc(w.name)}</h2><p>Choose the current fictional situation. Daggerheart only charges Stress when switching an inventory weapon in danger or under pressure.</p></div><button class="equip-dialog-close" type="button" data-close>×</button></div><div class="equip-contexts"><div class="equip-context"><strong>Calm / preparing</strong><p>Swap the weapon freely. This also applies while preparing during a rest.</p><button type="button" data-equip-context="calm">Equip free</button></div><div class="equip-context"><strong>Danger / under pressure</strong><p>Mark 1 Stress, then equip the inventory weapon. Hand limits are handled automatically.</p><button type="button" data-equip-context="danger">Mark 1 Stress & equip</button></div></div></div>`;d.querySelector('[data-close]')?.addEventListener('click',closeDialog);d.querySelector('[data-equip-context="calm"]')?.addEventListener('click',()=>equip(id,false));d.querySelector('[data-equip-context="danger"]')?.addEventListener('click',()=>equip(id,true));if(typeof d.showModal==='function'&&!d.open)d.showModal();else d.setAttribute('open','');}
  function ensureDialog(){let d=document.getElementById('equipmentDialog');if(!d){d=document.createElement('dialog');d.id='equipmentDialog';d.className='equipment-dialog';(document.getElementById('characterPageView')||document.body).appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}return d;}
  function closeDialog(){document.getElementById('equipmentDialog')?.close();}

  function useConsumable(id){if(isPreview())return;const item=cfg().consumables[id],count=state.consumables[id]||0,api=resourceAPI(),rs=resources();if(!item||count<1||!api||!rs)return;const current=Number(rs[item.kind]||0);if(current<=0){alert(`${cfg().name} has no marked ${item.kind==='hp'?'HP':'Stress'} to clear.`);return;}const roll=die(4),cleared=Math.min(roll,current);api.setResource?.(item.kind,current-cleared,`${item.name} · clear ${roll}`);lastConsumableResult=`${item.name}: rolled ${roll}; cleared ${cleared} ${item.kind==='hp'?'HP':'Stress'}.`;commit({consumables:{...state.consumables,[id]:count-1}},`Used ${item.name}`);}
  function adjustConsumable(id,delta){if(isPreview()||!cfg().consumables[id])return;const count=Math.max(0,Math.min(5,(state.consumables[id]||0)+Number(delta||0)));commit({consumables:{...state.consumables,[id]:count}},`${delta>0?'Add':'Remove'} ${cfg().consumables[id].name}`);}

  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let p=document.getElementById('equipmentManager');if(!p){p=document.createElement('section');p.id='equipmentManager';p.className='equipment-manager';const domain=document.getElementById('domainManager'),conditions=document.getElementById('conditionsPanel'),rest=document.getElementById('restPanel');(domain||conditions||rest||identity).insertAdjacentElement(domain||conditions||rest?'afterend':'beforeend',p);}return p;}
  function activeItem(id,label){const w=weapon(id);if(!id||!w)return`<div class="equip-item inventory"><span>${label.toUpperCase()}</span><strong>Empty</strong><em>No ${label.toLowerCase()} weapon equipped.</em></div>`;return`<div class="equip-item active"><span>ACTIVE ${label.toUpperCase()}</span><strong>${esc(w.name)}</strong><p>${esc(w.meta)}</p><em>${w.burden===2?'Two-Handed':'One-Handed'}</em></div>`;}
  function inventoryItem(id){const w=weapon(id);if(!w)return'';return`<div class="equip-item inventory"><span>INVENTORY WEAPON</span><strong>${esc(w.name)}</strong><p>${esc(w.meta)}</p><em>${w.burden===2?'Two-Handed':'One-Handed'} · ${w.slot}</em><div class="equip-item-actions"><button type="button" data-equip="${id}" ${isPreview()?'disabled':''}>Equip</button></div></div>`;}
  function consumableItem(id){const item=cfg().consumables[id],count=state.consumables[id]||0,rs=resources(),canUse=count>0&&Number(rs?.[item.kind]||0)>0;return`<div class="equip-item"><span>CONSUMABLE</span><strong>${esc(item.name)}</strong><p>${esc(item.effect)} · one use.</p><div class="equip-item-actions"><button type="button" data-consume="${id}" ${isPreview()||!canUse?'disabled':''}>Use</button><button type="button" data-consume-adjust="${id}" data-delta="-1" ${isPreview()||count<=0?'disabled':''}>−</button><b class="consumable-count">${count}</b><button type="button" data-consume-adjust="${id}" data-delta="1" ${isPreview()||count>=5?'disabled':''}>+</button></div></div>`;}
  function renderPanel(){const p=ensurePanel();if(!p)return;const inventory=state.inventoryWeapons.map(inventoryItem).join(''),consumables=Object.keys(cfg().consumables).map(consumableItem).join(''),gear=cfg().gear.map(g=>`<div class="equip-item inventory"><span>GEAR</span><strong>${esc(g)}</strong></div>`).join('');p.innerHTML=`<div class="equipment-head"><div><span>LIVE EQUIPMENT</span><strong>Weapons, Gear & Consumables</strong><small data-equipment-sync-label>${isPreview()?'GM preview · read only':'Equipped items determine active weapon features'}</small></div></div><div class="equipment-grid"><section class="equip-section"><div class="equip-section-title"><span>EQUIPPED</span><strong>Ready now</strong></div><div class="equip-list">${activeItem(state.activePrimary,'Primary')}${activeItem(state.activeSecondary,'Secondary')}<div class="equip-item active"><span>ACTIVE ARMOR</span><strong>${esc(cfg().armor.name)}</strong></div></div></section><section class="equip-section"><div class="equip-section-title"><span>PACK</span><strong>Inventory</strong></div><div class="equip-list">${inventory||'<div class="domain-empty">No inventory weapons.</div>'}${consumables}${gear}</div></section></div>${lastConsumableResult?`<div class="consumable-result">${esc(lastConsumableResult)}</div>`:''}<div class="equipment-rule"><b>Weapon switching:</b> free while calm or preparing during a rest; mark 1 Stress when equipping an inventory weapon in danger. A two-handed primary cannot be active with a secondary weapon.</div>`;p.querySelectorAll('[data-equip]').forEach(b=>b.addEventListener('click',()=>openEquip(b.dataset.equip)));p.querySelectorAll('[data-consume]').forEach(b=>b.addEventListener('click',()=>useConsumable(b.dataset.consume)));p.querySelectorAll('[data-consume-adjust]').forEach(b=>b.addEventListener('click',()=>adjustConsumable(b.dataset.consumeAdjust,Number(b.dataset.delta))));}

  function activeWeaponIds(){return new Set([state.activePrimary,state.activeSecondary].filter(Boolean));}
  function titleOf(node){return node.querySelector('strong')?.textContent.trim()||node.querySelector('h3')?.textContent.trim()||'';}
  function applyActionAvailability(){const active=activeWeaponIds(),offActions=new Set();for(const [id,w] of Object.entries(cfg().weapons))if(!active.has(id))for(const a of w.actions)offActions.add(a);document.querySelectorAll('#activeActionsPanel .active-action-card,#companionActionsPanel .active-action-card').forEach(n=>{const off=offActions.has(titleOf(n));n.classList.toggle('equipment-action-disabled',off);if(off){if(!n.disabled)n.dataset.equipmentDisabled='true';n.disabled=true;n.title='Weapon is not equipped.';}else if(n.dataset.equipmentDisabled==='true'){n.disabled=false;delete n.dataset.equipmentDisabled;n.removeAttribute('title');}});if(activeKey==='odie')document.querySelectorAll('#companionActionsPanel [data-paired]').forEach(box=>{const paired=state.activeSecondary==='small-dagger'&&Boolean(state.activePrimary)&&weapon(state.activePrimary)?.burden===1;box.checked=paired&&box.checked;box.disabled=!paired;box.closest('label')?.classList.toggle('equipment-action-disabled',!paired);if(!paired)box.title='Paired requires the Small Dagger active alongside a one-handed primary weapon.';});}
  function applyMarekArmor(){if(activeKey!=='marek')return;const node=[...document.querySelectorAll('#characterSheet .character-stat')].find(n=>n.querySelector('span')?.textContent.trim().toLowerCase()==='armor');const strong=node?.querySelector('strong');if(!strong)return;const target=document.body.classList.contains('marek-beastform-active')?3:(state.activeSecondary==='round-shield'?4:3);if(Number(String(strong.textContent).match(/\d+/)?.[0])!==target)strong.textContent=String(target);}
  function apply(){if(!state)return;applyActionAvailability();applyMarekArmor();}
  function render(){if(!state)return;renderPanel();apply();}
  function watch(){observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>{if(activeKey){apply();if(!document.getElementById('equipmentManager'))renderPanel();}}));observer.observe(document.getElementById('characterSheet')||document.body,{childList:true,subtree:true,characterData:true});}
  function init(){const k=key();if(!k){activeKey=null;state=null;observer?.disconnect();return;}load(k);if(!resourceAPI()||!document.querySelector('#characterSheet .character-sheet-shell')){setTimeout(init,120);return;}render();watch();}
  window.GreywakeEquipment={get key(){return activeKey;},getState:snapshot,importState,render,equip,adjustConsumable,isEquipped:id=>Boolean(state&&(state.activePrimary===id||state.activeSecondary===id))};
  const schedule=()=>setTimeout(init,380);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('greywake:resources-changed',()=>{if(activeKey)renderPanel();});window.addEventListener('greywake:companion-resources-changed',()=>{if(activeKey)renderPanel();});document.addEventListener('DOMContentLoaded',schedule);
})();