(() => {
  const CONFIG = {
    odie: {
      name:'Odie', maxHope:6, maxStress:6, maxHP:6,
      experiences:[['Repair',3],['Scavenger',2]],
      actions:[
        {id:'spear',title:'Spear',type:'attack',trait:'Finesse',meta:'Very Close · 1d8+3 physical',damage:{count:1,sides:8,mod:3,type:'physical'},body:'Odie’s primary weapon.'},
        {id:'dagger',title:'Small Dagger',type:'attack',trait:'Finesse',meta:'Melee · 1d8 physical',damage:{count:1,sides:8,mod:0,type:'physical'},body:'Inventory weapon. Paired can add +2 to primary-weapon damage against a target within Melee range.'},
        {id:'rain',title:'Rain of Blades',type:'attack',trait:'Finesse',meta:'Spellcast · Very Close · d8+2 magic',damage:{count:1,sides:8,mod:2,type:'magic'},cost:{resource:'hope',amount:1},body:'Spend a Hope, make a Spellcast Roll, and strike targets within Very Close range. Vulnerable targets take an extra 1d8 damage.'},
        {id:'pick',title:'Pick and Pull',type:'ability',trait:'Finesse',advantage:true,meta:'Midnight · advantage',body:'Advantage on action rolls to pick nonmagical locks, disarm nonmagical traps, or steal items from a target.'},
        {id:'shadow',title:'Shadow Stepper',type:'ability',cost:{resource:'stress',amount:1},meta:'Nightwalker · mark 1 Stress',body:'Move from one shadow to another within Far range and become Cloaked.'},
        {id:'dodge',title:'Rogue’s Dodge',type:'ability',cost:{resource:'hope',amount:3},meta:'Hope feature · spend 3 Hope',effect:'rogueDodge',body:'Gain +2 Evasion until the next attack succeeds against Odie, or until the next rest.'},
        {id:'cloaked',title:'Cloaked',type:'ability',meta:'Rogue class feature',body:'Whenever Odie would be Hidden, he is Cloaked instead.'},
        {id:'sneak',title:'Sneak Attack',type:'ability',meta:'Tier 1 · +1d6 damage',body:'On a successful attack while Cloaked, or while an ally is within Melee range of the target, add 1d6 to damage.'},
        {id:'lowlight',title:'Low-Light Living',type:'ability',meta:'Underborne · advantage',body:'In low light or heavy shadow, gain advantage on rolls to hide, investigate, or perceive details.'}
      ]
    },
    velmira: {
      name:'Velmira', maxHope:6, maxStress:7, maxHP:5,
      experiences:[['Friend to All',2],['Fake It Till You Make It',2]],
      actions:[
        {id:'greatstaff',title:'Greatstaff',type:'attack',trait:'Knowledge',meta:'Very Far · 1d6 magic · Powerful',damage:{count:1,sides:6,mod:0,type:'magic',powerful:true},body:'Powerful: on a successful attack, roll one additional damage die and discard the lowest result.'},
        {id:'whip',title:'Whip',type:'attack',trait:'Presence',meta:'Very Close · 1d6 physical',damage:{count:1,sides:6,mod:0,type:'physical'},body:'Startling can mark 1 Stress to force adversaries within Melee range back to Close range.'},
        {id:'powerpush',title:'Power Push',type:'attack',trait:'Knowledge',meta:'Spellcast · Melee · d10+2 magic',damage:{count:1,sides:10,mod:2,type:'magic'},body:'On a successful Spellcast Roll, knock the target back to Far range and deal d10+2 magic damage.'},
        {id:'dustspike',title:'Dust Spike',type:'attack',trait:'Knowledge',difficulty:12,meta:'Spellcast · Far · d6 physical',damage:{count:1,sides:6,mod:0,type:'physical'},body:'Greywake presentation of Book of Ava’s spike working. Make a Spellcast Roll (12), or roll against the target’s Difficulty when using it as a weapon.'},
        {id:'tava',title:'Tava’s Armor',type:'ability',cost:{resource:'hope',amount:1},meta:'Book of Ava · spend 1 Hope',body:'Give a creature you can touch +1 Armor Score until its next rest or until you cast Tava’s Armor again.'},
        {id:'mending',title:'Mending Touch',type:'ability',cost:{resource:'hope',amount:2},meta:'Splendor · spend 2 Hope',body:'After a few minutes of focused healing, clear 1 HP or 1 Stress on the creature you are helping. The once-per-long-rest shared-moment benefit can clear 2 instead.'},
        {id:'reassurance',title:'Reassurance',type:'ability',meta:'Splendor · once per rest',body:'After an ally attempts an action roll but before consequences resolve, offer support so they may reroll their dice.'},
        {id:'notthis',title:'Not This Time',type:'ability',cost:{resource:'hope',amount:3},meta:'Hope feature · spend 3 Hope',body:'Force an adversary within Far range to reroll an attack or damage roll.'},
        {id:'prestidigitation',title:'Prestidigitation',type:'ability',meta:'Wizard class feature',body:'Perform harmless, subtle magical effects at will.'},
        {id:'nomadic',title:'Nomadic Pack',type:'ability',cost:{resource:'hope',amount:1},meta:'Wanderborne · once per session',body:'Spend a Hope to pull out a mundane item useful to the current situation, agreeing the item with the GM.'},
        {id:'startling',title:'Startling',type:'ability',cost:{resource:'stress',amount:1},meta:'Whip feature · mark 1 Stress',body:'Crack the whip and force all adversaries within Melee range back to Close range.'}
      ]
    }
  };

  let activeKey=null, state=null, selectedAction=null;
  const storageKey=k=>`greywake:resources:${k}:v1`;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[ch]));
  const die=sides=>{if(window.crypto?.getRandomValues){const b=new Uint32Array(1);window.crypto.getRandomValues(b);return(b[0]%sides)+1;}return Math.floor(Math.random()*sides)+1;};
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return CONFIG[k]?k:null;}
  function cfg(){return CONFIG[activeKey]||null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}

  function load(k){
    if(!CONFIG[k])return null;
    if(activeKey===k&&state)return state;
    activeKey=k;
    const c=CONFIG[k];
    const base={hope:2,maxHope:c.maxHope,stress:0,maxStress:c.maxStress,hp:0,maxHP:c.maxHP,history:[],effects:{rogueDodge:false,strangePatternChosen:false},strangePattern:1};
    try{state={...base,...JSON.parse(localStorage.getItem(storageKey(k))||'null')};}catch(_){state=base;}
    state.maxHope=c.maxHope;state.maxStress=c.maxStress;state.maxHP=c.maxHP;
    state.hope=clamp(state.hope,0,state.maxHope);state.stress=clamp(state.stress,0,state.maxStress);state.hp=clamp(state.hp,0,state.maxHP);
    state.history=Array.isArray(state.history)?state.history.slice(-20):[];
    state.effects={rogueDodge:false,strangePatternChosen:false,...(state.effects||{})};
    state.strangePattern=clamp(state.strangePattern||1,1,12);
    return state;
  }
  function save(){try{localStorage.setItem(storageKey(activeKey),JSON.stringify(state));}catch(_){}}
  function snapshot(){return state?{hope:state.hope,maxHope:state.maxHope,stress:state.stress,maxStress:state.maxStress,hp:state.hp,maxHP:state.maxHP,vulnerable:state.stress>=state.maxStress,effects:{...state.effects},strangePattern:state.strangePattern}:null;}
  function notice(text,type='info'){
    let n=document.getElementById('companionNotice');
    if(!n){n=document.createElement('div');n.id='companionNotice';n.className='resource-notice';n.setAttribute('aria-live','polite');document.getElementById('characterPageView')?.appendChild(n);}
    if(!n)return;n.className=`resource-notice ${type} visible`;n.textContent=text;clearTimeout(notice.t);notice.t=setTimeout(()=>n.classList.remove('visible'),2400);
  }
  function renderResourcesOnly(){if(!activeKey||!state)return;updateStats();renderBoard();document.body.classList.toggle('resource-vulnerable',snapshot().vulnerable);}
  function commit(next,reason,extra={}){
    if(!state)return{ok:false};const before=snapshot();state.history.push({before,reason,at:Date.now()});state.history=state.history.slice(-20);Object.assign(state,next);
    state.hope=clamp(state.hope,0,state.maxHope);state.stress=clamp(state.stress,0,state.maxStress);state.hp=clamp(state.hp,0,state.maxHP);save();
    renderResourcesOnly();
    const detail={ok:true,key:activeKey,reason,before,after:snapshot(),...extra};window.dispatchEvent(new CustomEvent('greywake:companion-resources-changed',{detail}));return detail;
  }
  function spendHope(n=1,reason='Spend Hope'){n=Math.max(0,Number(n)||0);if(state.hope<n){notice(`Not enough Hope. ${n} required; ${cfg().name} has ${state.hope}.`,'error');return{ok:false,message:'Not enough Hope.'};}const r=commit({hope:state.hope-n},reason,{resource:'hope',amount:-n});notice(`−${n} Hope · ${r.after.hope}/${r.after.maxHope}`,'hope');return r;}
  function gainHope(n=1,reason='Gain Hope'){n=Math.max(0,Number(n)||0);const a=Math.min(n,state.maxHope-state.hope);if(!a)return{ok:true,capped:true,after:snapshot()};const r=commit({hope:state.hope+a},reason,{resource:'hope',amount:a});notice(`+${a} Hope · ${r.after.hope}/${r.after.maxHope}`,'hope');return r;}
  function markStress(n=1,{reason='Mark Stress',cost=false}={}){n=Math.max(0,Number(n)||0);const free=state.maxStress-state.stress;if(cost&&free<n){notice('No free Stress slot for that move.','error');return{ok:false,message:'No free Stress slot.'};}const mark=Math.min(n,free),overflow=n>free,hp=overflow?Math.min(state.maxHP,state.hp+1):state.hp;const r=commit({stress:state.stress+mark,hp},reason,{resource:'stress',amount:mark,overflow});notice(`Marked ${mark} Stress · ${r.after.stress}/${r.after.maxStress}${overflow?' · +1 HP overflow':''}${r.after.vulnerable?' · VULNERABLE':''}`,'stress');return r;}
  function clearStress(n=1,reason='Clear Stress'){const a=Math.min(Math.max(0,Number(n)||0),state.stress);if(!a)return{ok:true,after:snapshot()};const r=commit({stress:state.stress-a},reason,{resource:'stress',amount:-a});notice(`Cleared ${a} Stress · ${r.after.stress}/${r.after.maxStress}`,'stress');return r;}
  function setResource(resource,value,reason='Manual adjustment'){if(!state)return{ok:false};if(resource==='hope')return commit({hope:clamp(value,0,state.maxHope)},reason,{resource});if(resource==='stress')return commit({stress:clamp(value,0,state.maxStress)},reason,{resource});if(resource==='hp')return commit({hp:clamp(value,0,state.maxHP)},reason,{resource});return{ok:false};}
  function undo(){const e=state?.history.pop();if(!e){notice('Nothing to undo.');return;}const h=state.history;state={...state,...e.before,history:h};save();renderResourcesOnly();window.dispatchEvent(new CustomEvent('greywake:companion-resources-changed',{detail:{ok:true,key:activeKey,reason:`Undo: ${e.reason}`,after:snapshot()}}));notice(`Undid: ${e.reason}`);}
  function setEffect(name,value,reason){const r=commit({effects:{...state.effects,[name]:Boolean(value)}},reason||name,{effect:name});renderActions();return r;}
  function setStrangePattern(value){const v=clamp(value,1,12);const r=commit({strangePattern:v,effects:{...state.effects,strangePatternChosen:true}},'Set Strange Patterns number',{setting:'strangePattern'});renderActions();return r;}

  function statNode(label){return[...document.querySelectorAll('#characterSheet .character-stat')].find(n=>n.querySelector('span')?.textContent.trim().toLowerCase()===label.toLowerCase())||null;}
  function ensureHopeStat(){const strip=document.querySelector('#characterSheet .character-stat-strip');if(!strip||statNode('Hope'))return;const n=document.createElement('div');n.className='character-stat pro-stat-resource';n.innerHTML='<span>Hope</span><strong>2 / 6</strong>';strip.appendChild(n);}
  function updateStats(){ensureHopeStat();const s=snapshot();if(!s)return;const hp=statNode('HP')||statNode('HP max'),st=statNode('Stress')||statNode('Stress max'),hope=statNode('Hope');if(hp?.querySelector('strong'))hp.querySelector('strong').textContent=`${s.hp} / ${s.maxHP} marked`;if(st?.querySelector('strong'))st.querySelector('strong').textContent=`${s.stress} / ${s.maxStress} marked`;if(hope?.querySelector('strong'))hope.querySelector('strong').textContent=`${s.hope} / ${s.maxHope}`;if(activeKey==='odie'){const ev=statNode('Evasion');if(ev?.querySelector('strong'))ev.querySelector('strong').textContent=String(13+(state.effects.rogueDodge?2:0));ev?.classList.toggle('companion-effect-active',state.effects.rogueDodge);}}
  function pips(resource,current,max){return Array.from({length:max},(_,i)=>`<button type="button" class="live-resource-pip ${i<current?'filled':''}" data-companion-set="${resource}" data-value="${i+1}" aria-pressed="${i<current?'true':'false'}"></button>`).join('');}
  function row(resource,label,current,max,sub){return `<div class="live-resource-row live-resource-${resource}"><div class="live-resource-copy"><span>${label}</span><strong>${current}<small> / ${max}</small></strong><em>${esc(sub)}</em></div><div class="live-resource-controls"><button type="button" data-companion-adjust="${resource}" data-delta="-1">−</button><div class="live-resource-pips">${pips(resource,current,max)}</div><button type="button" data-companion-adjust="${resource}" data-delta="1">+</button></div></div>`;}
  function bindBoard(board){
    if(board.dataset.companionBound==='true')return;board.dataset.companionBound='true';
    board.addEventListener('click',e=>{
      const b=e.target.closest('button');if(!b||!board.contains(b))return;
      if(b.matches('[data-companion-adjust]')){const r=b.dataset.companionAdjust,d=Number(b.dataset.delta),s=snapshot();if(r==='hope')d>0?gainHope(d,'Manual Hope adjustment'):spendHope(Math.min(-d,s.hope),'Manual Hope adjustment');if(r==='stress')d>0?markStress(d,{reason:'Manual Stress adjustment'}):clearStress(Math.min(-d,s.stress),'Manual Stress adjustment');if(r==='hp')setResource('hp',s.hp+d,'Manual HP adjustment');return;}
      if(b.matches('[data-companion-set]')){const r=b.dataset.companionSet,v=Number(b.dataset.value),s=snapshot(),cur=r==='hope'?s.hope:r==='stress'?s.stress:s.hp;setResource(r,cur===v?v-1:v,`Set ${r}`);return;}
      if(b.matches('[data-companion-undo]'))undo();
    });
  }
  function patchResourceRow(board,resource,current,max){
    const r=board.querySelector(`.live-resource-${resource}`);if(!r)return;
    const strong=r.querySelector('.live-resource-copy strong');if(strong&&strong.dataset.value!==`${current}/${max}`){strong.dataset.value=`${current}/${max}`;strong.innerHTML=`${current}<small> / ${max}</small>`;}
    r.querySelectorAll(`[data-companion-set="${resource}"]`).forEach(p=>{const filled=Number(p.dataset.value)<=current;p.classList.toggle('filled',filled);p.setAttribute('aria-pressed',filled?'true':'false');});
  }
  function renderBoard(){
    const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return;
    let board=identity.querySelector('.pro-resource-board');if(!board){board=document.createElement('div');board.className='pro-resource-board live-resource-board';identity.appendChild(board);}board.classList.add('live-resource-board');const s=snapshot();
    const hasBase=board.querySelector('.pro-board-title')&&board.querySelector('.live-resource-hope')&&board.querySelector('.live-resource-stress')&&board.querySelector('.live-resource-hp')&&board.querySelector('.live-resource-foot');
    if(!hasBase){board.innerHTML=`<div class="pro-board-title"><span>LIVE FIELD CONDITION</span><small>${isPreview()?'GM preview · local test · not synced':'Greywake tracks these resources'}</small></div>${row('hope','Hope',s.hope,s.maxHope,'Experiences and Hope features')}${row('stress','Stress',s.stress,s.maxStress,'marked slots')}${row('hp','HP',s.hp,s.maxHP,'marked Hit Points')}<div class="live-resource-foot"><span class="live-resource-condition ${s.vulnerable?'active':''}">${s.vulnerable?'VULNERABLE · last Stress marked':'Stable · Stress slots remain'}</span><button type="button" data-companion-undo>Undo last change</button></div>`;}
    bindBoard(board);
    patchResourceRow(board,'hope',s.hope,s.maxHope);patchResourceRow(board,'stress',s.stress,s.maxStress);patchResourceRow(board,'hp',s.hp,s.maxHP);
    const note=board.querySelector('.pro-board-title small');if(note)note.textContent=isPreview()?'GM preview · local test · not synced':'Greywake tracks these resources';
    const condition=board.querySelector('.live-resource-condition');if(condition){condition.classList.toggle('active',s.vulnerable);condition.textContent=s.vulnerable?'VULNERABLE · last Stress marked':'Stable · Stress slots remain';}
  }

  function actionIcon(type){return type==='attack'?'⚔':'✦';}
  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let root=document.getElementById('companionActionsPanel');if(!root){root=document.createElement('section');root.id='companionActionsPanel';root.className='active-actions-panel companion-actions-panel';const board=identity.querySelector('.pro-resource-board');if(board)board.insertAdjacentElement('afterend',root);else identity.appendChild(root);}return root;}
  function actionCard(a){return `<button type="button" class="active-action-card active-action-${a.type} ${selectedAction===a.id?'selected':''}" data-companion-action="${a.id}"><span class="active-action-icon">${actionIcon(a.type)}</span><span class="active-action-copy"><small>${a.type==='attack'?'ACTIVE ATTACK':'ACTIVE ABILITY'}</small><strong>${esc(a.title)}</strong><em>${esc(a.meta||'')}</em></span><span class="active-action-arrow">›</span></button>`;}
  function experienceMarkup(){return `<fieldset class="action-roll-experiences"><legend>Experiences <small>${activeKey==='velmira'?'Hope or Adept Stress':'1 Hope each'}</small></legend>${cfg().experiences.map(([name,bonus],i)=>`<label><input type="checkbox" data-comp-exp="${i}" data-bonus="${bonus}"><span><b>${esc(name)}</b><small>+${bonus}</small></span></label>`).join('')}</fieldset>`;}
  function rollSetup(a){if(!a.trait)return'';return `<section class="action-roller"><div class="action-roller-head"><div><span>DUALITY ROLLER</span><strong>${a.type==='attack'?'Attack Roll':`${esc(a.trait)} Roll`}</strong><small>${esc(a.trait)} ${currentTrait(a.trait)>=0?'+':''}${currentTrait(a.trait)}</small></div><div class="action-roll-dice-preview"><i>H</i><i>F</i></div></div><div class="action-roll-setup">${experienceMarkup()}${activeKey==='velmira'?`<label class="companion-adept-choice"><span>Experience payment</span><select data-exp-payment><option value="hope">Spend Hope normally</option><option value="adept">Adept · mark Stress, double Experience</option></select></label>`:''}<div class="action-roll-fields"><label><span>Roll mode</span><select data-roll-mode><option value="normal" ${a.advantage?'':'selected'}>Normal</option><option value="advantage" ${a.advantage?'selected':''}>Advantage +d6</option><option value="disadvantage">Disadvantage −d6</option></select>${a.advantage?'<small class="action-roll-auto">This action grants Advantage</small>':''}</label><label><span>Other modifier</span><input data-roll-modifier type="number" value="0" min="-20" max="20"></label><label><span>Difficulty ${a.difficulty?'(default)':'(optional)'}</span><input data-roll-difficulty type="number" value="${a.difficulty??''}" min="1" max="40" placeholder="GM target"></label></div></div><button class="action-roll-button" type="button" data-companion-roll>${a.type==='attack'?'Roll Attack':`Roll ${esc(a.trait)}`}</button><div class="action-roll-result" data-roll-result aria-live="polite"></div></section>`;}
  function detail(a){const effect=(activeKey==='odie'&&a.effect==='rogueDodge'&&state.effects.rogueDodge)?`<div class="companion-effect-banner"><b>ACTIVE</b><span>Odie currently has +2 Evasion from Rogue’s Dodge.</span><button type="button" data-end-effect="rogueDodge">End effect</button></div>`:'';const use=(!a.trait&&a.cost)?`<div class="resource-action-use"><button type="button" data-use-action>${a.cost.resource==='hope'?'Spend':'Mark'} ${a.cost.amount} ${a.cost.resource==='hope'?'Hope':'Stress'} · Use ${esc(a.title)}</button><small>${esc(a.body)}</small></div>`:(!a.trait?`<div class="companion-no-roll"><strong>No roll required</strong><p>${esc(a.body)}</p></div>`:'');return `<div class="active-action-detail"><div class="active-action-detail-mark">${actionIcon(a.type)}</div><div class="active-action-detail-copy"><small>${a.type==='attack'?'ATTACK':'ABILITY'} · AVAILABLE NOW</small><h3>${esc(a.title)}</h3><p class="active-action-detail-meta">${esc(a.meta||'')}</p><p>${esc(a.body||'')}</p></div>${effect}${use}${rollSetup(a)}<div class="active-action-detail-tools"><button type="button" class="active-action-detail-close">Close</button></div></div>`;}
  function renderActions(){
    const root=ensurePanel();if(!root)return;const actions=cfg().actions;if(selectedAction&&!actions.some(a=>a.id===selectedAction))selectedAction=null;const a=actions.find(x=>x.id===selectedAction);
    const patternChosen=Boolean(state.effects?.strangePatternChosen);
    root.innerHTML=`<div class="active-actions-head"><div><span>READY REFERENCE</span><strong>Active Actions</strong><small>${cfg().name} · attacks and abilities available now</small></div><b>${actions.length}</b></div>${activeKey==='velmira'?`<div class="companion-pattern"><span>STRANGE PATTERNS</span><label>Chosen Duality number <select data-pattern-number><option value="">Choose</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${patternChosen&&state.strangePattern===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><small>When this appears on either Duality Die, choose to gain 1 Hope or clear 1 Stress.</small></div>`:''}<div class="active-actions-zone"><div class="active-actions-column active-actions-attacks"><div class="active-actions-label"><span>ATTACKS</span><small>Use now</small></div>${actions.filter(x=>x.type==='attack').map(actionCard).join('')}</div><div class="active-actions-column active-actions-abilities"><div class="active-actions-label"><span>ABILITIES</span><small>Use now</small></div>${actions.filter(x=>x.type!=='attack').map(actionCard).join('')}</div></div>${a?detail(a):''}`;
    root.querySelectorAll('[data-companion-action]').forEach(b=>b.addEventListener('click',()=>{selectedAction=selectedAction===b.dataset.companionAction?null:b.dataset.companionAction;renderActions();}));
    root.querySelector('.active-action-detail-close')?.addEventListener('click',()=>{selectedAction=null;renderActions();});
    root.querySelector('[data-pattern-number]')?.addEventListener('change',e=>{if(e.target.value)setStrangePattern(Number(e.target.value));});
    root.querySelector('[data-use-action]')?.addEventListener('click',()=>useAction(a));
    root.querySelector('[data-end-effect]')?.addEventListener('click',()=>setEffect('rogueDodge',false,'End Rogue’s Dodge'));
    root.querySelector('[data-companion-roll]')?.addEventListener('click',()=>performRoll(root,a,false));
  }
  function currentTrait(name){const c=[...document.querySelectorAll('#characterSheet .sheet-grid.traits .sheet-card')].find(x=>x.querySelector('h4')?.textContent.trim()===name);const m=String(c?.querySelector('.sheet-value')?.textContent||'').match(/[+−-]?\d+/);return m?Number(m[0].replace('−','-')):0;}
  function payCost(cost,reason){if(!cost)return{ok:true};return cost.resource==='hope'?spendHope(cost.amount,reason):markStress(cost.amount,{reason,cost:true});}
  function useAction(a){if(!a)return;const r=payCost(a.cost,a.title);if(!r.ok)return;if(a.effect==='rogueDodge')setEffect('rogueDodge',true,'Rogue’s Dodge active');else notice(`${a.title} used.`);renderActions();}
  const experienceBonus=checked=>checked.reduce((sum,i)=>sum+Number(i.dataset.bonus||0),0);
  function payExperiences(host,reroll){const checked=[...host.querySelectorAll('[data-comp-exp]:checked')];if(reroll){const adept=activeKey==='velmira'&&(host.querySelector('[data-exp-payment]')?.value||'hope')==='adept';return{ok:true,checked,bonus:experienceBonus(checked)*(adept?2:1),mode:adept?'adept':'hope'};}const mode=activeKey==='velmira'?(host.querySelector('[data-exp-payment]')?.value||'hope'):'hope';if(!checked.length)return{ok:true,checked,bonus:0,mode};if(mode==='adept'){const r=markStress(checked.length,{reason:'Adept Experience use',cost:true});if(!r.ok)return{ok:false};return{ok:true,checked,bonus:experienceBonus(checked)*2,mode};}const r=spendHope(checked.length,'Experience use');if(!r.ok)return{ok:false};return{ok:true,checked,bonus:experienceBonus(checked),mode};}
  function bindRollResultClose(result){result?.querySelector('[data-close-roll-result]')?.addEventListener('click',()=>result.replaceChildren());}
  function performRoll(root,a,reroll=false){
    const host=root.querySelector('.active-action-detail');if(!host||!a?.trait)return;
    const expCount=host.querySelectorAll('[data-comp-exp]:checked').length,payment=activeKey==='velmira'?(host.querySelector('[data-exp-payment]')?.value||'hope'):'hope';
    if(!reroll){const hopeNeeded=(a.cost?.resource==='hope'?a.cost.amount:0)+(payment==='hope'?expCount:0),stressNeeded=(a.cost?.resource==='stress'?a.cost.amount:0)+(payment==='adept'?expCount:0);if(hopeNeeded>state.hope){notice(`${hopeNeeded} Hope required for this roll; only ${state.hope} available.`,'error');return;}if(stressNeeded>(state.maxStress-state.stress)){notice(`${stressNeeded} free Stress slot${stressNeeded===1?'':'s'} required for this roll.`,'error');return;}if(a.cost){const paid=payCost(a.cost,a.title);if(!paid.ok)return;}}
    const exp=payExperiences(host,reroll);if(!exp.ok)return;
    const trait=currentTrait(a.trait),hope=die(12),fear=die(12),critical=hope===fear,axis=critical||hope>fear?'Hope':'Fear',mode=host.querySelector('[data-roll-mode]')?.value||'normal',advDie=mode==='normal'?0:die(6),adv=mode==='advantage'?advDie:mode==='disadvantage'?-advDie:0,other=clamp(host.querySelector('[data-roll-modifier]')?.value||0,-20,20),difficultyRaw=host.querySelector('[data-roll-difficulty]')?.value,difficulty=difficultyRaw?clamp(difficultyRaw,1,40):null,total=hope+fear+trait+exp.bonus+adv+other,success=critical?true:difficulty==null?null:total>=difficulty;
    if(critical){gainHope(1,'Critical success');clearStress(1,'Critical success');}else if(axis==='Hope')gainHope(1,'Roll with Hope');
    const result=host.querySelector('[data-roll-result]');if(!result)return;const headline=critical?'CRITICAL SUCCESS':success==null?`${total} WITH ${axis.toUpperCase()}`:`${success?'SUCCESS':'FAILURE'} WITH ${axis.toUpperCase()}`;const parts=[`${hope} Hope`,`${fear} Fear`,`${a.trait} ${trait>=0?'+':''}${trait}`];if(exp.bonus)parts.push(`Experience +${exp.bonus}${exp.mode==='adept'?' (Adept)':''}`);if(mode!=='normal')parts.push(`${mode==='advantage'?'Advantage':'Disadvantage'} ${adv>=0?'+':''}${adv}`);if(other)parts.push(`Other ${other>=0?'+':''}${other}`);
    const pattern=activeKey==='velmira'&&state.effects?.strangePatternChosen&&(hope===state.strangePattern||fear===state.strangePattern),adapt=success===false&&exp.checked.length>0;
    result.innerHTML=`<div class="duality-result ${critical?'critical':axis.toLowerCase()}"><button type="button" class="action-roll-result-close" data-close-roll-result>Close result ×</button><div class="duality-dice"><div class="hope-die"><span>HOPE</span><b>${hope}</b></div><div class="fear-die"><span>FEAR</span><b>${fear}</b></div></div><div class="duality-outcome"><span>${esc(a.title)}</span><strong>${headline}</strong><b>Total ${total}${difficulty?` / Difficulty ${difficulty}`:''}</b><small>${critical?'Gain 1 Hope · clear 1 Stress':axis==='Hope'?'Gain 1 Hope':'GM gains 1 Fear'}</small></div><p class="duality-breakdown">${parts.map(esc).join(' · ')}</p>${pattern?`<div class="companion-pattern-trigger"><strong>Strange Patterns · ${state.strangePattern}</strong><span>Choose one:</span><button type="button" data-pattern-gain>Gain 1 Hope</button><button type="button" data-pattern-clear>Clear 1 Stress</button></div>`:''}${adapt?`<button class="companion-adaptability" type="button" data-adapt-reroll>Adaptability · mark 1 Stress and reroll</button>`:''}${a.damage&&success!==false?damageControls(a,critical):''}</div>`;
    bindRollResultClose(result);result.querySelector('[data-pattern-gain]')?.addEventListener('click',e=>{gainHope(1,'Strange Patterns');e.currentTarget.parentElement.remove();});result.querySelector('[data-pattern-clear]')?.addEventListener('click',e=>{clearStress(1,'Strange Patterns');e.currentTarget.parentElement.remove();});result.querySelector('[data-adapt-reroll]')?.addEventListener('click',()=>{const r=markStress(1,{reason:'Adaptability reroll',cost:true});if(r.ok)performRoll(root,a,true);});result.querySelector('[data-roll-damage]')?.addEventListener('click',()=>rollDamage(result,a,critical));
  }
  function damageControls(a,critical){const extras=activeKey==='odie'?`<label><input type="checkbox" data-sneak> Sneak Attack +1d6</label>${a.id==='rain'?'<label><input type="checkbox" data-vulnerable> Target Vulnerable +1d8</label>':''}`:'';return `<div class="damage-roll-controls companion-damage"><button type="button" data-roll-damage>${critical?'Roll Critical Damage':'Roll Damage'}</button><span>${a.damage.count}d${a.damage.sides}${a.damage.mod?(a.damage.mod>0?'+':'')+a.damage.mod:''} ${esc(a.damage.type)}</span>${extras}</div><div data-damage-result></div>`;}
  function rollDamage(result,a,critical){const d=a.damage;let rolls=[],base=0;if(d.powerful){const r1=die(d.sides),r2=die(d.sides);rolls=[r1,r2];base=Math.max(r1,r2)+d.mod;}else{rolls=Array.from({length:d.count},()=>die(d.sides));base=rolls.reduce((x,y)=>x+y,0)+d.mod;}let extra=0,notes=[];if(activeKey==='odie'){if(result.querySelector('[data-sneak]')?.checked){const r=die(6);extra+=r;notes.push(`Sneak d6: ${r}`);}if(result.querySelector('[data-vulnerable]')?.checked){const r=die(8);extra+=r;notes.push(`Vulnerable d8: ${r}`);}}const crit=critical?d.count*d.sides:0,total=base+extra+crit,host=result.querySelector('[data-damage-result]');if(host)host.innerHTML=`<div class="damage-roll-result ${critical?'critical':''}"><div><span>${critical?'CRITICAL DAMAGE':'DAMAGE'}</span><strong>${total}</strong><small>${esc(d.type)}</small></div><p>${d.powerful?`Powerful rolls ${rolls.join(' / ')}, keep ${Math.max(...rolls)}`:rolls.map(r=>`d${d.sides}: ${r}`).join(' · ')}${d.mod?` · ${d.mod>0?'+':''}${d.mod}`:''}${crit?` · critical +${crit}`:''}${notes.length?` · ${notes.join(' · ')}`:''}</p></div>`;}

  function renderAll(){if(!activeKey||!state)return;updateStats();renderBoard();renderActions();document.body.classList.remove('companion-readonly');document.body.classList.toggle('resource-vulnerable',snapshot().vulnerable);}
  function init(){const k=key();if(!k){activeKey=null;state=null;selectedAction=null;document.getElementById('companionActionsPanel')?.remove();return;}load(k);if(!document.querySelector('#characterSheet .character-sheet-shell'))return;const note=document.querySelector('#characterSheet .character-sheet-note');if(note)note.textContent='Greywake is the live play sheet for Hope, Stress and Hit Points. Rolls and fixed resource costs update these tracks automatically; player changes sync across devices.';renderAll();}

  window.GreywakeCompanion={get key(){return activeKey;},getState:snapshot,spendHope,gainHope,markStress,clearStress,setResource,undo,setEffect,setStrangePattern,importState(remote){if(!state||!remote)return;const next={hope:remote.hope,stress:remote.stress,hp:remote.hp};if(remote.effects)next.effects={...state.effects,...remote.effects};if(remote.strangePattern)next.strangePattern=remote.strangePattern;Object.assign(state,next);state.hope=clamp(state.hope,0,state.maxHope);state.stress=clamp(state.stress,0,state.maxStress);state.hp=clamp(state.hp,0,state.maxHP);save();renderResourcesOnly();if(remote.effects||remote.strangePattern)renderActions();}};
  let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(init,40);};
  window.addEventListener('greywake:player-ready',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);document.addEventListener('DOMContentLoaded',schedule);
})();