(() => {
  const API_URL='https://tmqxxgzqiccclcjagdsh.supabase.co/functions/v1/downtime';
  const API_KEY='sb_publishable_zML4qGtgQgMALEXFJn501w_1imfz8wl';
  const NAMES={marek:'Marek',velmira:'Velmira',odie:'Odie'};
  const SUGGESTIONS={marek:['Continue something I’m pursuing','Investigate something','Study or research something','Prepare for the next expedition','Nothing special'],odie:['Continue something I’m pursuing','Check the Digger tunnels','Work on or repair something','Investigate something','Prepare for the next expedition','Nothing special'],velmira:['Check on Nemi','Spend time with Tavi','Follow a Stilling lead','Work trade contacts','Prepare for the next expedition','Nothing special']};
  const style=document.createElement('style');
  style.textContent=`.downtime-panel{margin:28px 0;padding:22px;border:1px solid #665d45;background:linear-gradient(180deg,rgba(36,34,27,.96),rgba(24,23,19,.98));box-shadow:0 10px 30px rgba(0,0,0,.22)}.downtime-panel h2{margin:.2rem 0 .4rem}.downtime-kicker,.downtime-status{font-size:.75rem;letter-spacing:.13em;text-transform:uppercase;color:#cdbb79}.downtime-meta{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0}.downtime-pill{padding:5px 9px;border:1px solid #5d5541;border-radius:999px}.downtime-paused{border-color:#9b6b59;background:rgba(98,49,39,.15)}.downtime-actions{display:grid;gap:10px;margin-top:14px}.downtime-actions button,.downtime-actions input,.downtime-actions textarea,.downtime-actions select{font:inherit}.downtime-actions button{padding:9px 12px}.downtime-suggestions{display:flex;flex-wrap:wrap;gap:8px}.downtime-entry{border-top:1px solid #4d4738;padding:12px 0}.downtime-grid{display:grid;gap:12px}.downtime-gm-controls{display:flex;gap:8px;flex-wrap:wrap}.downtime-note{opacity:.78}.downtime-error{color:#e2a18e}`;
  document.head.appendChild(style);

  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  function currentUser(){return window.GreywakePlayer||null;}
  function identity(){const u=currentUser();if(!u)return null;const isPreview=document.body.dataset.gmPreview==='true';if(u.role==='gm'&&!isPreview)return{character:'gm',code:'GREYWAKE',role:'gm'};const slug=(document.body.dataset.character||u.character||'').toLowerCase();return{character:slug,code:String(u.code||NAMES[slug]||'').toUpperCase(),role:u.role};}
  async function req(method='GET',body=null){const id=identity();if(!id)throw new Error('Player identity unavailable.');const r=await fetch(API_URL,{method,headers:{apikey:API_KEY,'Content-Type':'application/json','x-greywake-character':id.character,'x-greywake-code':id.code},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Downtime update failed.');return d;}
  function ensureHost(){let host=document.getElementById('downtimePanel');if(host)return host;host=document.createElement('section');host.id='downtimePanel';host.className='downtime-panel';const home=document.getElementById('home');const hero=home?.querySelector('.hero');if(hero)hero.insertAdjacentElement('afterend',host);else home?.prepend(host);return host;}
  function stateLabel(s){return({waiting_gm:'Waiting on GM',waiting_player:'Waiting on player',resolved_today:'Resolved for today',live_scene:'Live scene',complete:'Complete'})[s]||s;}
  async function render(){const host=ensureHost();if(!host)return;const id=identity();if(!id){host.hidden=true;return;}host.hidden=false;host.innerHTML='<div class="downtime-kicker">EXTENDED DOWNTIME</div><p class="downtime-note">Loading shared timeline…</p>';
    try{const data=await req();const w=data.window,actions=data.actions||[];if(id.role==='gm'&&id.character==='gm')return renderGM(host,w,actions,id);return renderPlayer(host,w,actions,id);}catch(e){host.innerHTML=`<div class="downtime-kicker">EXTENDED DOWNTIME</div><p class="downtime-error">${esc(e.message)}</p>`;}}
  function renderPlayer(host,w,actions,id){if(!w){host.innerHTML='<div class="downtime-kicker">EXTENDED DOWNTIME</div><h2>No downtime window is open</h2><p class="downtime-note">You can still use interests and questions between sessions. Downtime only opens when the fiction has actually created spare time.</p>';return;}
    const a=actions.find(x=>x.day_number===w.current_day);const paused=w.status==='paused';host.innerHTML=`<div class="downtime-kicker">SHARED GREYWAKE CLOCK</div><h2>${esc(w.total_days)} day${w.total_days===1?'':'s'} in Greywake</h2><p>${esc(w.reason||'Time has opened up before the next major departure.')}</p><div class="downtime-meta"><span class="downtime-pill">Day ${w.current_day} of ${w.total_days}</span><span class="downtime-pill ${paused?'downtime-paused':''}">${paused?'Paused for live scene':'Timeline moving'}</span></div>${paused?`<p><strong>Shared clock paused.</strong> ${esc(w.pause_reason||'A live scene must be resolved before anyone moves further forward.')}</p>`:''}<div id="downtimePlayerBody"></div>`;
    const body=host.querySelector('#downtimePlayerBody');if(paused){if(a)body.innerHTML=entryMarkup(a);return;}if(a){body.innerHTML=entryMarkup(a)+(a.state==='waiting_player'?`<div class="downtime-actions"><textarea id="downtimeFocus" rows="3" placeholder="What does ${esc(NAMES[id.character]||'your character')} do next?"></textarea><button id="downtimeSubmit">Send next step</button></div>`:'');}
    else{const buttons=(SUGGESTIONS[id.character]||SUGGESTIONS.marek).map(x=>`<button type="button" data-dt-suggestion="${esc(x)}">${esc(x)}</button>`).join('');body.innerHTML=`<p><strong>What is the one thing ${esc(NAMES[id.character]||'your character')} wants to accomplish today?</strong></p><div class="downtime-suggestions">${buttons}</div><div class="downtime-actions"><textarea id="downtimeFocus" rows="3" maxlength="500" placeholder="A sentence is enough."></textarea><button id="downtimeSubmit">Use this as my focus</button></div>`;}
    host.querySelectorAll('[data-dt-suggestion]').forEach(b=>b.onclick=()=>{const t=host.querySelector('#downtimeFocus');if(t)t.value=b.dataset.dtSuggestion;});const submit=host.querySelector('#downtimeSubmit');if(submit)submit.onclick=async()=>{const t=host.querySelector('#downtimeFocus');const focus=t?.value.trim();if(!focus)return;t.disabled=submit.disabled=true;try{await req('POST',{action:'submit_focus',focus});await render();}catch(e){alert(e.message);t.disabled=submit.disabled=false;}};
  }
  function entryMarkup(a){return `<div class="downtime-entry"><div class="downtime-status">${esc(stateLabel(a.state))}</div><strong>${esc(a.focus_text)}</strong>${a.gm_response?`<p>${esc(a.gm_response)}</p>`:''}</div>`;}
  function renderGM(host,w,actions){if(!w){host.innerHTML=`<div class="downtime-kicker">GM · EXTENDED DOWNTIME</div><h2>No downtime window is open</h2><p>The fiction creates the opportunity; use this only when Greywake genuinely has spare time.</p><form id="dtOpen" class="downtime-actions"><select id="dtDays"><option value="1">1 day</option><option value="3" selected>3 days</option><option value="7">1 week</option></select><input id="dtReason" maxlength="500" placeholder="Why is this time available? e.g. Three days pass before the next expedition"><button>Open downtime window</button></form>`;host.querySelector('#dtOpen').onsubmit=async e=>{e.preventDefault();await req('POST',{action:'open_window',total_days:Number(host.querySelector('#dtDays').value),reason:host.querySelector('#dtReason').value});await render();};return;}
    const cards=['marek','velmira','odie'].map(slug=>{const a=actions.find(x=>x.character_slug===slug&&x.day_number===w.current_day);return `<div class="downtime-entry" data-dt-card="${slug}"><div class="downtime-status">${esc(NAMES[slug])} · ${a?esc(stateLabel(a.state)):'No focus yet'}</div>${a?`<strong>${esc(a.focus_text)}</strong>${a.gm_response?`<p>${esc(a.gm_response)}</p>`:''}<textarea rows="2" data-dt-response="${a.id}" placeholder="Routine result, information, or why this becomes a live scene"></textarea><div class="downtime-gm-controls"><button data-dt-state="resolved_today" data-id="${a.id}">Resolve today</button><button data-dt-state="waiting_player" data-id="${a.id}">Needs player</button><button data-dt-state="live_scene" data-id="${a.id}">Hold for live scene</button></div>`:'<p class="downtime-note">Waiting for player input.</p>'}</div>`;}).join('');
    host.innerHTML=`<div class="downtime-kicker">GM · SHARED GREYWAKE CLOCK</div><h2>Day ${w.current_day} of ${w.total_days}</h2><p>${esc(w.reason)}</p><div class="downtime-meta"><span class="downtime-pill ${w.status==='paused'?'downtime-paused':''}">${w.status==='paused'?'PAUSED — live scene':'OPEN — concurrent actions'}</span></div>${w.status==='paused'?`<p><strong>Do not advance anyone beyond this point.</strong> ${esc(w.pause_reason||'Resolve the live scene first.')}</p>`:''}<div class="downtime-grid">${cards}</div><div class="downtime-gm-controls">${w.status==='paused'?'<button id="dtResume">Scene resolved — resume shared clock</button>':'<button id="dtAdvance">Advance shared day</button>'}<button id="dtClose">Close downtime window</button></div>`;
    host.querySelectorAll('[data-dt-state]').forEach(b=>b.onclick=async()=>{const area=host.querySelector(`[data-dt-response="${b.dataset.id}"]`);b.disabled=true;try{await req('PATCH',{action:'resolve_action',id:Number(b.dataset.id),state:b.dataset.dtState,response:area?.value||''});await render();}catch(e){alert(e.message);b.disabled=false;}});const resume=host.querySelector('#dtResume');if(resume)resume.onclick=async()=>{await req('PATCH',{action:'resume'});await render();};const advance=host.querySelector('#dtAdvance');if(advance)advance.onclick=async()=>{try{await req('PATCH',{action:'advance_day'});await render();}catch(e){alert(e.message);}};host.querySelector('#dtClose').onclick=async()=>{await req('PATCH',{action:'close_window'});await render();};
  }
  window.addEventListener('greywake:player-ready',render);document.addEventListener('DOMContentLoaded',render);setTimeout(render,300);
})();