(() => {
  const CONFIG={marek:{name:'Marek'},velmira:{name:'Velmira'},odie:{name:'Odie'}};
  const STORAGE_PREFIX='greywake:conditions:v1:';
  let activeKey=null,state=null,observer=null,pendingUse=null;
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return CONFIG[k]?k:null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function resourceState(){return(activeKey==='marek'?window.GreywakeResources:window.GreywakeCompanion)?.getState?.()||null;}
  function base(){return{manualVulnerable:false,hidden:false,restrained:false,cloaked:false};}
  function load(k){if(!CONFIG[k])return null;if(activeKey===k&&state)return state;activeKey=k;try{state={...base(),...JSON.parse(localStorage.getItem(STORAGE_PREFIX+k)||'null')};}catch(_){state=base();}for(const p of Object.keys(base()))state[p]=Boolean(state[p]);return state;}
  function save(){try{localStorage.setItem(STORAGE_PREFIX+activeKey,JSON.stringify(state));}catch(_){}}
  function autoVulnerable(){const r=resourceState();return Boolean(r&&Number(r.stress)>=Number(r.maxStress));}
  function vulnerable(){return Boolean(state?.manualVulnerable||autoVulnerable());}
  function snapshot(){return state?{manualVulnerable:Boolean(state.manualVulnerable),hidden:Boolean(state.hidden),restrained:Boolean(state.restrained),cloaked:Boolean(state.cloaked),vulnerable:vulnerable(),autoVulnerable:autoVulnerable()}:null;}
  function commit(next,reason){if(!state)return;Object.assign(state,next);save();render();window.dispatchEvent(new CustomEvent('greywake:conditions-changed',{detail:{ok:true,key:activeKey,reason,state:snapshot()}}));}
  function importState(remote){if(!state||!remote)return;for(const p of ['manualVulnerable','hidden','restrained','cloaked'])if(remote[p]!==undefined)state[p]=Boolean(remote[p]);if(activeKey==='odie'&&state.hidden){state.cloaked=true;state.hidden=false;}save();render();}
  function setCondition(name,value,reason){if(isPreview())return;if(name==='hidden'&&activeKey==='odie')name='cloaked';commit({[name]:Boolean(value)},reason||`Set ${name}`);}

  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let p=document.getElementById('conditionsPanel');if(!p){p=document.createElement('section');p.id='conditionsPanel';p.className='conditions-panel';const rest=document.getElementById('restPanel');if(rest)rest.insertAdjacentElement('afterend',p);else{const damage=document.getElementById('damageHealthPanel');if(damage)damage.insertAdjacentElement('afterend',p);else identity.appendChild(p);}}return p;}
  function card(name,label,copy,active,extra=''){return `<div class="condition-card ${active?'active':''} ${extra}" data-condition-card="${name}"><span>CONDITION</span><strong>${label}</strong><p>${copy}</p>${name==='vulnerable'&&autoVulnerable()?'<small>Automatic: every Stress slot is marked.</small>':active?'<small>Currently active.</small>':'<small>Currently inactive.</small>'}<button type="button" data-condition-toggle="${name}" ${isPreview()||(name==='vulnerable'&&autoVulnerable()&&!state.manualVulnerable)?'disabled':''}>${active?(name==='vulnerable'&&autoVulnerable()&&!state.manualVulnerable?'Automatic from Stress':'Clear'):'Apply'}</button></div>`;}
  function renderPanel(){const p=ensurePanel();if(!p)return;const hideName=activeKey==='odie'?'Cloaked':'Hidden',hideKey=activeKey==='odie'?'cloaked':'hidden',hideActive=state[hideKey];p.innerHTML=`<div class="conditions-head"><div><span>LIVE CONDITIONS</span><strong>Position & Exposure</strong></div><small data-condition-sync-label>${isPreview()?'GM preview · read only':'Synced Daggerheart conditions'}</small></div><div class="conditions-grid">${card('vulnerable','Vulnerable','All rolls made against this character have advantage.',vulnerable(),autoVulnerable()?'auto':'')}${card(hideKey,hideName,activeKey==='odie'?'Cloaked includes Hidden’s protection: rolls against Odie have disadvantage. Odie also stays unseen while stationary when a foe moves into a normal sightline; attacking or ending a move in an adversary’s line of sight ends Cloaked.':'While out of sight and unlocated, rolls against this character have disadvantage.',hideActive)}${card('restrained','Restrained','Cannot move, but can still take actions from the current position.',state.restrained)}</div><div class="condition-chip-row"><span class="condition-chip ${vulnerable()?'active danger':''}">Vulnerable</span><span class="condition-chip ${hideActive?'active':''}">${hideName}</span><span class="condition-chip ${state.restrained?'active':''}">Restrained</span></div>`;
    p.querySelectorAll('[data-condition-toggle]').forEach(b=>b.addEventListener('click',()=>{let n=b.dataset.conditionToggle;if(n==='vulnerable')commit({manualVulnerable:!state.manualVulnerable},state.manualVulnerable?'Clear manual Vulnerable':'Apply Vulnerable');else commit({[n]:!state[n]},state[n]?`Clear ${n}`:`Apply ${n}`);}));
  }

  function applyGameplay(){const s=snapshot();if(!s)return;document.body.classList.toggle('condition-vulnerable',s.vulnerable);document.body.classList.toggle('condition-restrained',s.restrained);document.body.classList.toggle('condition-cloaked',activeKey==='odie'&&s.cloaked);document.body.classList.toggle('condition-hidden',activeKey!=='odie'&&s.hidden);
    if(activeKey==='odie'&&s.cloaked){document.querySelectorAll('#companionActionsPanel [data-sneak]').forEach(box=>{if(!box.dataset.conditionTouched){box.checked=true;box.dataset.conditionTouched='true';}});}
    if(s.restrained){[...document.querySelectorAll('#companionActionsPanel [data-companion-action]')].forEach(b=>{const title=b.querySelector('strong')?.textContent.trim();if(title==='Shadow Stepper'){if(!b.disabled)b.dataset.conditionDisabled='true';b.disabled=true;b.title='Restrained: Odie cannot move.';}});[...document.querySelectorAll('#activeActionsPanel .active-action-card')].forEach(b=>{const title=b.querySelector('strong')?.textContent.trim();if(title==='Agile'){if(!b.disabled)b.dataset.conditionDisabled='true';b.disabled=true;b.title='Restrained: cannot use movement.';}});}else document.querySelectorAll('[data-condition-disabled="true"]').forEach(b=>{b.disabled=false;delete b.dataset.conditionDisabled;b.removeAttribute('title');});
  }
  function render(){if(!activeKey||!state)return;renderPanel();applyGameplay();}

  function captureOdieActions(){document.addEventListener('click',event=>{
      if(activeKey!=='odie'||isPreview())return;
      const use=event.target.closest('#companionActionsPanel [data-use-action]');
      if(use){const detail=use.closest('.active-action-detail'),title=detail?.querySelector('h3')?.textContent.trim();if(title==='Shadow Stepper'){const before=resourceState()?.stress;pendingUse={title,before};setTimeout(()=>{const after=resourceState()?.stress;if(pendingUse?.title==='Shadow Stepper'&&Number(after)>Number(pendingUse.before))setCondition('cloaked',true,'Shadow Stepper · become Cloaked');pendingUse=null;},0);}}
      const roll=event.target.closest('#companionActionsPanel [data-companion-roll]');
      if(roll&&state?.cloaked){const detail=roll.closest('.active-action-detail'),isAttack=/ATTACK/i.test(detail?.querySelector('.active-action-detail-copy > small')?.textContent||''),result=detail?.querySelector('[data-roll-result]'),before=result?.innerHTML||'';if(isAttack)setTimeout(()=>{if(result&&result.innerHTML!==before)setCondition('cloaked',false,'Attack ends Cloaked');},0);}
    },true);}

  function init(){const k=key();if(!k){activeKey=null;state=null;observer?.disconnect();return;}load(k);if(!resourceState()){setTimeout(init,100);return;}if(activeKey==='odie'&&state.hidden){state.hidden=false;state.cloaked=true;save();}render();observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>{if(activeKey){applyGameplay();if(!document.getElementById('conditionsPanel'))renderPanel();}}));observer.observe(document.getElementById('characterSheet')||document.body,{childList:true,subtree:true});}
  window.GreywakeConditions={get key(){return activeKey;},getState:snapshot,importState,setCondition,render};
  captureOdieActions();const schedule=()=>setTimeout(init,230);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('greywake:resources-changed',()=>{if(activeKey){render();}});window.addEventListener('greywake:companion-resources-changed',()=>{if(activeKey){render();}});document.addEventListener('DOMContentLoaded',schedule);
})();