import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-greywake-code, x-greywake-character","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const CODES:any={marek:"MAREK",velmira:"VELMIRA",odie:"ODIE",gm:"GREYWAKE"},PCS=["marek","velmira","odie"],RK="system_resource_state",CK="system_cross_player_state";
const DEF:any={marek:{hope:2,maxHope:6,stress:0,maxStress:7,hp:0,maxHP:6},velmira:{hope:2,maxHope:6,stress:0,maxStress:7,hp:0,maxHP:5},odie:{hope:2,maxHope:6,stress:0,maxStress:6,hp:0,maxHP:6}};
const j=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,"Content-Type":"application/json"}}),norm=(v:any)=>String(v??"").trim().toLowerCase(),clean=(v:any,n=160)=>String(v??"").trim().replace(/\s+/g," ").slice(0,n),copy=(v:any)=>JSON.parse(JSON.stringify(v)),clamp=(v:any,a:number,b:number)=>Math.max(a,Math.min(b,Number(v)||0));
const validPC=(v:any)=>PCS.includes(norm(v)),validR=(v:any)=>v&&Number(v.v)===1&&[["hope","maxHope"],["stress","maxStress"],["hp","maxHP"]].every(([a,b])=>Number.isInteger(Number(v[a]))&&Number.isInteger(Number(v[b]))&&Number(v[b])>0&&Number(v[a])>=0&&Number(v[a])<=Number(v[b])),validC=(v:any)=>v&&Number(v.v)===1;
const baseC=()=>({v:1,revision:0,tavaArmor:null,mendingSharedUsed:false,clarityUsed:false,lastEvent:null}),rev=(s:any)=>Math.max(0,Number(s?.revision)||0)+1,die=(n:number)=>{const x=new Uint32Array(1);crypto.getRandomValues(x);return x[0]%n+1;};
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});
 const actor=norm(req.headers.get("x-greywake-character")),code=String(req.headers.get("x-greywake-code")||"").trim().toUpperCase();
 if(!PCS.includes(actor)||code!==CODES[actor])return j({error:"Invalid Greywake access code."},403);
 const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return j({error:"Server configuration missing."},500);
 const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 async function goal(pc:string,kind:string,create=false){let {data,error}=await db.from("player_goals").select("id,character_slug,source_kind,source_key").eq("character_slug",pc).eq("source_kind",kind).eq("source_key",pc).maybeSingle();if(error)throw error;if(data)return data;if(!create)throw new Error(`${pc} live state is unavailable.`);({data,error}=await db.from("player_goals").insert({character_slug:pc,goal_text:"System: Cross-player effects",entry_kind:"interest",source_kind:kind,source_key:pc,source_title:"Cross-player effects",status:"dormant",thread_state:"resolved"}).select("id,character_slug,source_kind,source_key").single());if(error)throw error;return data;}
 async function latest(g:any,validator:any){const {data,error}=await db.from("player_goal_messages").select("id,message_text").eq("goal_id",g.id).order("id",{ascending:false}).limit(80);if(error)throw error;for(const r of data||[])try{const s=JSON.parse(r.message_text);if(validator(s))return{id:Number(r.id),state:s};}catch{}return null;}
 async function rs(pc:string){const g=await goal(pc,RK),x=await latest(g,validR);return{g,id:x?.id||0,state:x?.state||{v:1,...DEF[pc],revision:0,source:"cross_effect_fallback"}};}
 async function cs(pc:string){const g=await goal(pc,CK,true),x=await latest(g,validC);return{g,id:x?.id||0,state:{...baseC(),...(x?.state||{})}};}
 async function insert(rows:any[]){if(!rows.length)return[];const at=new Date().toISOString(),payload=rows.map(r=>({goal_id:r.g.id,author_role:"player",message_kind:"reply",message_text:JSON.stringify({...r.state,at:r.state.at||at})})),{data,error}=await db.from("player_goal_messages").insert(payload).select("id,goal_id");if(error)throw error;await db.from("player_goals").update({updated_at:at}).in("id",[...new Set(rows.map(r=>r.g.id))]);return data||[];}
 function mutate(s:any,op:any){const n=copy(s);if(op.kind==="clear_hp"){const b=+n.hp||0;n.hp=op.all?0:Math.max(0,b-(+op.amount||0));return{n,a:b-n.hp};}if(op.kind==="clear_stress"){const b=+n.stress||0;n.stress=op.all?0:Math.max(0,b-(+op.amount||0));return{n,a:b-n.stress};}if(op.kind==="gain_hope"){const b=+n.hope||0;n.hope=Math.min(+n.maxHope||6,b+(+op.amount||0));return{n,a:n.hope-b};}if(op.kind==="spend_hope"){const b=+n.hope||0,a=+op.amount||0;if(b<a)throw new Error(`Not enough Hope. ${a} required; ${b} available on the synced sheet.`);n.hope=b-a;return{n,a};}if(op.kind==="repair_armor"){n.damage={...(n.damage||{})};const b=+n.damage.armorMarked||0;n.damage.armorMarked=op.all?0:Math.max(0,b-(+op.amount||0));return{n,a:b-n.damage.armorMarked};}throw new Error("Unsupported cross-player resource operation.");}
 async function write(id:string,source:string,R:Map<string,any>,C:Map<string,any>){const at=new Date().toISOString(),rr=[];for(const[pc,x]of R){x.n={...x.n,v:1,revision:rev(x.r.state),source:"cross_effect",reason:source,crossEffect:{...x.e,id,actor,target:pc,source,previousMessageId:x.r.id,at},at};rr.push({g:x.r.g,state:x.n});}const ri=await insert(rr),mid=new Map(ri.map((r:any)=>[+r.goal_id,+r.id])),cr=[];for(const[pc,x]of C){const ev=x.e?{...x.e,id,actor,target:pc,source,at,resourceMessageId:mid.get(R.get(pc)?.r.g.id)||null}:x.n.lastEvent;x.n={...baseC(),...x.n,v:1,revision:rev(x.r.state),lastEvent:ev??null,crossMeta:{id,actor,previousMessageId:x.r.id,at},source:"cross_effect",reason:source,at};cr.push({g:x.r.g,state:x.n});}await insert(cr);}
 try{
  if(req.method==="GET"){const[c,r]=await Promise.all([cs(actor),rs(actor)]);return j({state:c.state,crossMessageId:c.id,resource:{...r.state,messageId:r.id}});}
  if(req.method!=="POST")return j({error:"Method not allowed."},405);const body=await req.json();
  if(body.rest_completed){const c=await cs(actor),n:any={...c.state,tavaArmor:null,revision:rev(c.state),source:"rest_reset",reason:"Rest completed",at:new Date().toISOString()};if(norm(body.rest_completed.effective)==="long"){if(actor==="velmira")n.mendingSharedUsed=false;if(actor==="marek")n.clarityUsed=false;}await insert([{g:c.g,state:n}]);return j({ok:true,state:n});}
  if(body.undo_effect_id){const id=clean(body.undo_effect_id,80),undo=crypto.randomUUID(),now=new Date().toISOString(),RR:any[]=[],CC:any[]=[];async function find(g:any,val:any,key:string){const {data,error}=await db.from("player_goal_messages").select("id,message_text").eq("goal_id",g.id).order("id",{ascending:false}).limit(80);if(error)throw error;for(const row of data||[])try{const s=JSON.parse(row.message_text),m=s?.[key];if(val(s)&&m?.id===id&&m?.actor===actor)return{id:+row.id,state:s,meta:m};}catch{}return null;}async function prev(g:any,id:number,val:any,fallback:any=null){if(!id)return fallback?copy(fallback):null;const {data,error}=await db.from("player_goal_messages").select("message_text").eq("goal_id",g.id).eq("id",id).maybeSingle();if(error)throw error;try{const s=JSON.parse(data?.message_text||"");return val(s)?s:null;}catch{return null;}}
   for(const pc of PCS){const r=await rs(pc),e=await find(r.g,validR,"crossEffect");if(e){if(r.id!==e.id)return j({error:`Cannot safely undo: ${pc}'s resources changed after this effect.`},409);const p=await prev(r.g,+e.meta.previousMessageId,validR);if(!p)return j({error:"Earlier resource state is unavailable."},409);RR.push({pc,r,p});}const c=await cs(pc),ce=await find(c.g,validC,"crossMeta");if(ce){if(c.id!==ce.id)return j({error:`Cannot safely undo: ${pc}'s cross-player state changed after this effect.`},409);const p=await prev(c.g,+ce.meta.previousMessageId,validC,baseC());if(!p)return j({error:"Earlier cross-player state is unavailable."},409);CC.push({pc,c,p});}}
   if(!RR.length&&!CC.length)return j({error:"That effect was not found or is no longer safe to undo."},409);const rr=RR.map(x=>({g:x.r.g,state:{...copy(x.p),v:1,revision:rev(x.r.state),source:"cross_effect_undo",reason:`Undo ${id}`,crossEffect:{id:undo,actor,target:x.pc,type:"undo",undoOf:id,previousMessageId:x.r.id,at:now},at:now}})),ri=await insert(rr),mids=new Map(ri.map((r:any)=>[+r.goal_id,+r.id]));await insert(CC.map(x=>({g:x.c.g,state:{...baseC(),...copy(x.p),v:1,revision:rev(x.c.state),source:"cross_effect_undo",reason:`Undo ${id}`,lastEvent:{id:undo,actor,target:x.pc,type:"undo",undoOf:id,source:`Undo ${id}`,at:now,resourceMessageId:mids.get(RR.find(y=>y.pc===x.pc)?.r.g.id)||null},crossMeta:{id:undo,actor,previousMessageId:x.c.id,undoOf:id,at:now},at:now}})));const[aR,aC]=await Promise.all([rs(actor),cs(actor)]);return j({ok:true,effectId:undo,undone:id,summary:"Cross-player effect undone.",actorState:aC.state,resource:{...aR.state,messageId:aR.id}});
  }
  const e=body.effect;if(!e)return j({error:"No cross-player effect supplied."},400);const type=norm(e.type),source=clean(e.source||type),id=crypto.randomUUID(),R=new Map(),C=new Map();
  async function ec(pc:string){if(!C.has(pc)){const r=await cs(pc);C.set(pc,{r,n:copy(r.state)});}return C.get(pc);}async function ar(pc:string,op:any,event:any){const r=R.get(pc)?.r||await rs(pc),b=R.get(pc)?.n||r.state,{n,a}=mutate(b,op);R.set(pc,{r,n,e:{...event,requested:op.all?"all":Math.max(0,+op.amount||0),actual:a,all:!!op.all}});const c=await ec(pc);c.e={...event,requested:op.all?"all":Math.max(0,+op.amount||0),actual:a,all:!!op.all};return a;}
  let target=actor,roll=null,summary="";
  if(type==="mending_touch"){if(actor!=="velmira")return j({error:"Only Velmira can use Mending Touch."},403);if(!validPC(e.target))return j({error:"Choose Marek, Velmira or Odie."},400);target=norm(e.target);const resource=norm(e.resource),amount=+e.amount===2?2:1;if(!["hp","stress"].includes(resource))return j({error:"Mending Touch must clear HP or Stress."},400);await ar(actor,{kind:"spend_hope",amount:2},{type:"ability_cost",resource:"hope",label:"Mending Touch · 2 Hope"});const c=await ec(actor);if(amount===2){if(c.n.mendingSharedUsed)return j({error:"The shared-moment Mending Touch is already used until Velmira completes a Long Rest."},409);c.n.mendingSharedUsed=true;}const a=await ar(target,{kind:resource==="hp"?"clear_hp":"clear_stress",amount},{type,resource,label:"Mending Touch"});summary=`Mending Touch · ${target} cleared ${a} ${resource==="hp"?"HP":"Stress"}.`;
  }else if(type==="tavas_armor"){if(actor!=="velmira")return j({error:"Only Velmira can use Tava's Armor."},403);if(!validPC(e.target))return j({error:"Choose Marek, Velmira or Odie."},400);target=norm(e.target);await ar(actor,{kind:"spend_hope",amount:1},{type:"ability_cost",resource:"hope",label:"Tava's Armor · 1 Hope"});for(const pc of PCS){const c=await cs(pc),n=copy(c.state);let changed=false;if(n.tavaArmor?.source==="velmira"){n.tavaArmor=null;changed=true;}if(pc===target){n.tavaArmor={source:"velmira",bonus:1,effectId:id,at:new Date().toISOString()};changed=true;}if(changed)C.set(pc,{r:c,n,e:{type,resource:"armor",label:"Tava's Armor",bonus:pc===target?1:0}});}summary=`Tava's Armor · ${target} gains +1 Armor Score until their next rest or until Velmira casts it again.`;
  }else if(type==="regeneration"){if(actor!=="marek")return j({error:"Only Marek can use Regeneration."},403);if(!validPC(e.target))return j({error:"Choose Marek, Velmira or Odie."},400);target=norm(e.target);await ar(actor,{kind:"spend_hope",amount:3},{type:"ability_cost",resource:"hope",label:"Regeneration · 3 Hope"});roll=die(4);const a=await ar(target,{kind:"clear_hp",amount:roll},{type,resource:"hp",label:"Regeneration",roll});summary=`Regeneration · d4 ${roll} · ${target} cleared ${a} HP.`;
  }else if(type==="clarity_of_nature"){if(actor!=="marek")return j({error:"Only Marek can use Clarity of Nature."},403);const c=await ec(actor);if(c.n.clarityUsed)return j({error:"Clarity of Nature is already used until Marek completes a Long Rest."},409);const m=new Map();for(const x of Array.isArray(e.allocations)?e.allocations:[]){if(!validPC(x.target))return j({error:"Clarity targets must be Marek, Velmira or Odie."},400);const pc=norm(x.target);m.set(pc,(m.get(pc)||0)+clamp(x.amount,0,2));}if([...m.values()].reduce((a,b)=>a+b,0)!==2)return j({error:"Clarity of Nature must distribute exactly 2 Stress recovery."},400);c.n.clarityUsed=true;const parts=[];for(const[pc,amount]of m){target=pc;parts.push(`${pc} ${await ar(pc,{kind:"clear_stress",amount},{type,resource:"stress",label:"Clarity of Nature"})}`);}summary=`Clarity of Nature · Stress cleared: ${parts.join(", ")}.`;
  }else if(type==="rest_clear_hp"||type==="rest_repair_armor"){if(!validPC(e.target))return j({error:"Choose a valid ally."},400);target=norm(e.target);if(target===actor)return j({error:"Choose another PC for a cross-player rest effect."},400);const all=!!e.all,kind=type==="rest_clear_hp"?"clear_hp":"repair_armor",label=clean(e.label|| (kind==="clear_hp"?"Tend to Wounds":"Repair Armor")),a=await ar(target,{kind,amount:all?0:clamp(e.amount,0,20),all},{type,resource:kind==="clear_hp"?"hp":"armor",label});summary=`${label} · ${target} ${kind==="clear_hp"?`cleared ${a} HP`:`repaired ${a} Armor Slot${a===1?"":"s"}`}.`;
  }else if(type==="rest_prepare"){const pcs=[...new Set((Array.isArray(e.targets)?e.targets:[]).map((x:any)=>norm(x)).filter((x:string)=>validPC(x)))].filter((x:string)=>x!==actor) as string[],amount=clamp(e.amount,1,4);if(!pcs.length)return j({error:"Choose at least one other character preparing with you."},400);const parts=[];for(const pc of pcs){target=pc;parts.push(`${pc} +${await ar(pc,{kind:"gain_hope",amount},{type,resource:"hope",label:"Prepare Together"})}`);}summary=`Prepare Together · ${parts.join(", ")} Hope.`;
  }else return j({error:"That cross-player effect is not supported."},400);
  for(const[pc,x]of R)if(!C.has(pc)){const c=await cs(pc);C.set(pc,{r:c,n:copy(c.state),e:x.e});}await write(id,source,R,C);const[aC,aR,tC,tR]=await Promise.all([cs(actor),rs(actor),cs(target),rs(target)]);return j({ok:true,effectId:id,summary,roll,actorState:aC.state,actorResource:{...aR.state,messageId:aR.id},target,targetState:tC.state,targetResource:{...tR.state,messageId:tR.id}});
 }catch(error){console.error(error);return j({error:error instanceof Error?error.message:"Unexpected cross-player effect error."},500);}
});
