(() => {
  const API_URL='https://tmqxxgzqiccclcjagdsh.supabase.co/functions/v1/player-goals?include_system=1';
  const API_KEY='sb_publishable_zML4qGtgQgMALEXFJn501w_1imfz8wl';
  const SYSTEM_KIND='system_condition_state';
  const POLL_MS=5000;
  let activeKey=null,systemGoalId=null,lastServerMessageId=0,remoteRevision=0,applying=false,pushPending=false,pushTimer=null,pollTimer=null,initialized=false;
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return['marek','velmira','odie'].includes(k)?k:null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function identity(){const user=window.GreywakePlayer,character=key(),code=String(user?.code||character||'').toUpperCase();return{character,code};}
  async function request(method='GET',body=null){const auth=identity();if(!auth.character||!auth.code)throw new Error('Greywake condition sync identity is unavailable.');const res=await fetch(API_URL,{method,headers:{apikey:API_KEY,'Content-Type':'application/json','x-greywake-character':auth.character,'x-greywake-code':auth.code},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Greywake condition state could not sync.');return data;}
  function localState(){const s=window.GreywakeConditions?.getState?.();if(!s)return null;return{manualVulnerable:Boolean(s.manualVulnerable),hidden:Boolean(s.hidden),restrained:Boolean(s.restrained),cloaked:Boolean(s.cloaked)};}
  function valid(v){return Boolean(v&&Number(v.v)===1&&['manualVulnerable','hidden','restrained','cloaked'].every(p=>typeof v[p]==='boolean'));}
  function same(a,b){return a&&b&&['manualVulnerable','hidden','restrained','cloaked'].every(p=>Boolean(a[p])===Boolean(b[p]));}
  function parseLatest(bundle){const goals=Array.isArray(bundle?.goals)?bundle.goals:[],messages=Array.isArray(bundle?.messages)?bundle.messages:[];const g=goals.find(x=>x?.character_slug===activeKey&&x?.source_kind===SYSTEM_KIND&&x?.source_key===activeKey);if(!g)return null;systemGoalId=Number(g.id);const candidates=messages.filter(m=>Number(m.goal_id)===systemGoalId).sort((a,b)=>Number(b.id)-Number(a.id));for(const m of candidates){try{const p=JSON.parse(m.message_text);if(valid(p))return{...p,messageId:Number(m.id)};}catch(_){}}return null;}
  function label(text,error=false){const n=document.querySelector('#conditionsPanel [data-condition-sync-label]');if(n){n.textContent=text;n.classList.toggle('condition-sync-error',error);}}
  function applyRemote(remote){const api=window.GreywakeConditions,current=localState();if(!api||!current||!valid(remote)||same(current,remote))return;applying=true;try{api.importState(remote);}finally{applying=false;}}
  async function pull({initial=false}={}){if(!activeKey||!window.GreywakeConditions)return;if(pushPending&&!isPreview()){await push('Reconnect pending conditions');if(pushPending)return;}try{const remote=parseLatest(await request('GET'));if(!remote)throw new Error('Condition sync record missing.');remoteRevision=Math.max(remoteRevision,Number(remote.revision)||0);const local=localState(),untouched=remote.source==='initial_import'&&Number(remote.revision)<=1;if(initial&&!isPreview()&&untouched&&local&&!same(local,remote)){lastServerMessageId=Number(remote.messageId)||0;await push('First condition sync','local_migration');return;}if(Number(remote.messageId)>lastServerMessageId){applyRemote(remote);lastServerMessageId=Number(remote.messageId)||lastServerMessageId;}label(isPreview()?'GM preview · live conditions · read only':'Conditions synced across devices');}catch(error){label('Local conditions · sync will retry',true);console.warn('Greywake condition sync pull failed:',error);}}
  async function push(reason='Condition update',source='client'){if(!activeKey||isPreview()||applying)return;const s=localState();if(!s)return;try{if(!systemGoalId){const remote=parseLatest(await request('GET'));if(!remote||!systemGoalId)throw new Error('Condition sync record unavailable.');remoteRevision=Math.max(remoteRevision,Number(remote.revision)||0);lastServerMessageId=Math.max(lastServerMessageId,Number(remote.messageId)||0);}const payload={v:1,...s,revision:remoteRevision+1,source,reason:String(reason||'Condition update').slice(0,120),at:new Date().toISOString()};const result=await request('POST',{goal_id:systemGoalId,message:JSON.stringify(payload),kind:'reply'});remoteRevision=payload.revision;if(result?.message?.id)lastServerMessageId=Number(result.message.id);pushPending=false;label('Conditions synced across devices');}catch(error){pushPending=true;label('Local condition change waiting to sync',true);console.warn('Greywake condition sync push failed:',error);}}
  function schedulePush(event){if(applying||isPreview()||!activeKey)return;pushPending=true;clearTimeout(pushTimer);pushTimer=setTimeout(()=>push(event?.detail?.reason||'Condition update'),450);}
  function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&activeKey)pull();},POLL_MS);}
  async function init(){const k=key();if(!k){activeKey=null;clearInterval(pollTimer);return;}if(activeKey!==k){activeKey=k;systemGoalId=null;lastServerMessageId=0;remoteRevision=0;pushPending=false;initialized=false;}if(!window.GreywakeConditions||window.GreywakeConditions.key!==k){setTimeout(init,120);return;}startPolling();await pull({initial:true});initialized=true;}
  window.addEventListener('greywake:conditions-changed',schedulePush);window.addEventListener('greywake:player-ready',()=>setTimeout(init,280));window.addEventListener('focus',()=>{if(initialized&&activeKey)pull();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&initialized&&activeKey)pull();});document.addEventListener('DOMContentLoaded',()=>setTimeout(init,320));
})();