(() => {
  const PEOPLE={marek:'Marek',velmira:'Velmira',odie:'Odie'};
  const TRAITS={
    marek:{Agility:1,Strength:0,Finesse:1,Instinct:2,Presence:-1,Knowledge:0},
    velmira:{Agility:-1,Strength:0,Finesse:0,Instinct:1,Presence:1,Knowledge:2},
    odie:{Agility:1,Strength:1,Finesse:2,Instinct:0,Presence:-1,Knowledge:0}
  };
  const PREFIX='greywake:teamwork:v1:';
  let activeKey=null,state=null,tagDraft=null;
  const die=sides=>{if(window.crypto?.getRandomValues){const b=new Uint32Array(1);window.crypto.getRandomValues(b);return(b[0]%sides)+1;}return Math.floor(Math.random()*sides)+1;};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return PEOPLE[k]?k:null;}
  function name(k=activeKey){return PEOPLE[k]||k;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function resourceAPI(k=activeKey){if(k!==activeKey)return null;return k==='marek'?window.GreywakeResources:window.GreywakeCompanion;}
  function resources(){return resourceAPI()?.getState?.()||null;}
  function base(){return{tagUsed:false,tagPartner:null};}
  function load(k){activeKey=k;let s=null;try{s=JSON.parse(localStorage.getItem(PREFIX+k)||'null');}catch(_){}state={...base(),...(s||{})};state.tagUsed=Boolean(state.tagUsed);save();return state;}
  function save(){try{localStorage.setItem(PREFIX+activeKey,JSON.stringify(state));}catch(_){}}
  function snapshot(){return state?{tagUsed:Boolean(state.tagUsed),tagPartner:state.tagPartner||null}:null;}
  function commit(next,reason){Object.assign(state,next);save();render();window.dispatchEvent(new CustomEvent('greywake:teamwork-state-changed',{detail:{ok:true,key:activeKey,reason,state:snapshot()}}));}
  function importState(remote){if(!remote)return;state={...state,tagUsed:Boolean(remote.tagUsed),tagPartner:remote.tagPartner||null};save();render();}
  function spendHope(n,reason){const api=resourceAPI(),rs=resources();if(!api||!rs||Number(rs.hope)<n){alert(`${name()} needs ${n} Hope for that.`);return false;}return api.spendHope?.(n,reason)?.ok!==false;}
  function gainHope(n,reason){resourceAPI()?.gainHope?.(n,reason);}
  function clearStress(n,reason){const api=resourceAPI(),rs=resources();if(api&&rs)api.setResource?.('stress',Math.max(0,Number(rs.stress)-n),reason);}
  function allies(){return Object.keys(PEOPLE).filter(k=>k!==activeKey);}
  function householdFriend(){if(activeKey!=='marek')return false;try{return JSON.parse(localStorage.getItem('greywake:marek:beastform:v1')||'null')?.active==='household-friend';}catch(_){return false;}}
  function currentTrait(k,trait){if(k!==activeKey)return Number(TRAITS[k]?.[trait]||0);const card=[...document.querySelectorAll('#characterSheet .sheet-grid.traits .sheet-card')].find(c=>c.querySelector('h4')?.textContent.trim()===trait),m=String(card?.querySelector('.sheet-value')?.textContent||'').match(/[+−-]?\d+/);return m?Number(m[0].replace('−','-')):Number(TRAITS[k]?.[trait]||0);}

  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let p=document.getElementById('partyActions');if(!p){p=document.createElement('section');p.id='partyActions';p.className='party-actions';const equipment=document.getElementById('equipmentManager'),domain=document.getElementById('domainManager');(equipment||domain||identity).insertAdjacentElement(equipment||domain?'afterend':'beforeend',p);}return p;}
  function render(){const p=ensurePanel();if(!p||!state)return;const rs=resources(),canHelp=!isPreview()&&Number(rs?.hope||0)>=1,canTag=!isPreview()&&!state.tagUsed&&Number(rs?.hope||0)>=3;p.innerHTML=`<div class="party-actions-head"><div><span>PARTY ACTIONS</span><strong>Work Together</strong><small data-team-sync-label>${isPreview()?'GM preview · read only':'Hope-powered cooperation'}</small></div></div><div class="party-actions-grid"><div class="party-action-card"><span>1 HOPE</span><strong>Help an Ally</strong><p>Describe the help, spend 1 Hope and roll an advantage die for an ally’s action roll.${householdFriend()?' Household Friend upgrades Marek’s die to d8.':''}</p><button type="button" data-team-action="help" ${canHelp?'':'disabled'}>Help an Ally</button></div><div class="party-action-card"><span>GROUP ROLL</span><strong>Group Action</strong><p>Track reaction successes and failures, then apply the net modifier to the leader’s action roll.</p><button type="button" data-team-action="group" ${isPreview()?'disabled':''}>Calculate Group Action</button></div><div class="party-action-card ${state.tagUsed?'tag-used':''}"><span>3 HOPE · ONCE / SESSION</span><strong>Tag Team Roll</strong><p>${state.tagUsed?`Already initiated${state.tagPartner?` with ${name(state.tagPartner)}`:''} this session.`:'Combine two PCs into one scene-defining roll and choose which Duality result applies to both.'}</p><button type="button" data-team-action="tag" ${canTag?'':'disabled'}>${state.tagUsed?'Used this session':'Initiate Tag Team'}</button>${state.tagUsed&&!isPreview()?'<button type="button" data-reset-tag style="margin-top:.4rem">New session · reset</button>':''}</div></div>`;p.querySelector('[data-team-action="help"]')?.addEventListener('click',openHelp);p.querySelector('[data-team-action="group"]')?.addEventListener('click',openGroup);p.querySelector('[data-team-action="tag"]')?.addEventListener('click',openTag);p.querySelector('[data-reset-tag]')?.addEventListener('click',()=>{if(confirm('Reset this character’s once-per-session Tag Team use?'))commit({tagUsed:false,tagPartner:null},'New session · reset Tag Team');});}
  function ensureDialog(){let d=document.getElementById('teamDialog');if(!d){d=document.createElement('dialog');d.id='teamDialog';d.className='team-dialog';(document.getElementById('characterPageView')||document.body).appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}return d;}
  function head(title,copy){return`<div class="team-dialog-head"><div><span>PARTY ACTION</span><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><button class="team-dialog-close" type="button" data-close>×</button></div>`;}
  function showDialog(html){const d=ensureDialog();d.innerHTML=`<div class="team-dialog-shell">${html}</div>`;d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());if(typeof d.showModal==='function'&&!d.open)d.showModal();else d.setAttribute('open','');return d;}
  function openHelp(){const dieSize=householdFriend()?8:6,d=showDialog(`${head('Help an Ally','Spend Hope only when you commit to the help. If the ally has several advantage dice, they keep the highest result.')}<div class="team-form"><label>Who are you helping?<select data-help-ally>${allies().map(k=>`<option value="${k}">${name(k)}</option>`).join('')}</select></label><label>How are you helping?<textarea data-help-copy rows="2" placeholder="Briefly describe the support"></textarea></label><button class="team-primary" type="button" data-help-roll>Spend 1 Hope · Roll d${dieSize}</button></div><div data-team-result></div><div class="team-rule-note">This rolls the helper’s advantage die only; it does not replace the ally’s action roll.</div>`);d.querySelector('[data-help-roll]')?.addEventListener('click',()=>{if(!spendHope(1,'Help an Ally'))return;const result=die(dieSize),ally=d.querySelector('[data-help-ally]').value,copy=d.querySelector('[data-help-copy]').value.trim();d.querySelector('[data-team-result]').innerHTML=`<div class="help-result"><strong>${name()} helps ${name(ally)}</strong><div class="help-die"><b>${result}</b></div><p>Add <b>+${result}</b> as the advantage result if it is the highest advantage die rolled.${copy?` ${esc(copy)}`:''}</p></div>`;d.querySelector('[data-help-roll]').disabled=true;render();});}
  function openGroup(){const d=showDialog(`${head('Group Action','The leader makes the action roll after the other participants make reaction rolls.')}<div class="team-form"><label>Successful reaction rolls<input data-group-success type="number" min="0" max="2" value="0"></label><label>Failed reaction rolls<input data-group-fail type="number" min="0" max="2" value="0"></label></div><div data-team-result class="group-result"><strong>Leader modifier: +0</strong><p>Add +1 per reaction success and −1 per reaction failure.</p></div>`);const update=()=>{const s=Math.max(0,Math.min(2,Number(d.querySelector('[data-group-success]').value)||0)),f=Math.max(0,Math.min(2,Number(d.querySelector('[data-group-fail]').value)||0)),mod=s-f;d.querySelector('[data-team-result]').innerHTML=`<strong>Leader modifier: ${mod>=0?'+':''}${mod}</strong><p>${s} success${s===1?'':'es'} · ${f} failure${f===1?'':'s'}. Enter this as the leader’s Other Modifier on their action roll.</p>`;};d.querySelectorAll('input').forEach(i=>i.addEventListener('input',update));}

  function traitOptions(k){return Object.keys(TRAITS[k]).map(t=>`<option value="${t}">${t} ${currentTrait(k,t)>=0?'+':''}${currentTrait(k,t)}</option>`).join('');}
  function openTag(){const d=showDialog(`${head('Tag Team Roll','Choose a partner. Spending 3 Hope starts the once-per-session roll; both sides then roll before either result is resolved.')}<div class="team-form"><label>Partner<select data-tag-partner>${allies().map(k=>`<option value="${k}">${name(k)}</option>`).join('')}</select></label><label><span><input data-tag-attack type="checkbox"> This is an attack Tag Team</span></label><button class="team-primary" type="button" data-start-tag>Spend 3 Hope · Begin Tag Team</button></div><div data-tag-workflow></div>`);d.querySelector('[data-start-tag]')?.addEventListener('click',()=>{const partner=d.querySelector('[data-tag-partner]').value;if(!spendHope(3,'Initiate Tag Team Roll'))return;commit({tagUsed:true,tagPartner:partner},`Tag Team initiated with ${name(partner)}`);tagDraft={partner,attack:d.querySelector('[data-tag-attack]').checked,rolls:{}};renderTagWorkflow(d);});}
  function sideMarkup(k){return`<div class="tag-side" data-tag-side="${k}"><strong>${name(k)}</strong><div class="tag-side-grid"><select data-tag-trait>${traitOptions(k)}</select><input data-tag-mod type="number" value="0" min="-20" max="20" title="Other modifiers"></div><label style="display:block;margin-top:.45rem;font-size:.7rem;color:#887f70">Roll mode <select data-tag-mode style="width:100%;min-height:36px;margin-top:.2rem;background:#0e0f0c;color:#ddd3bd"><option value="normal">Normal</option><option value="advantage">Advantage +d6</option><option value="disadvantage">Disadvantage −d6</option></select></label><button class="team-primary" type="button" data-roll-tag-side="${k}" style="width:100%;margin-top:.5rem">Roll ${name(k)}</button><div class="tag-roll-display" data-tag-roll-display>Not rolled.</div></div>`;}
  function renderTagWorkflow(d){const partner=tagDraft.partner;d.querySelector('[data-tag-workflow]').innerHTML=`<div class="tag-rollers">${sideMarkup(activeKey)}${sideMarkup(partner)}</div><div class="tag-choose"><button type="button" data-choose-tag="${activeKey}" disabled>Use ${name()} result</button><button type="button" data-choose-tag="${partner}" disabled>Use ${name(partner)} result</button></div><div data-tag-result></div><div class="team-rule-note">Each side may use a different trait. “Other modifiers” can hold agreed Experience or situational modifiers; any Hope/Stress cost belonging to the partner must be marked on that player’s own sheet.</div>`;d.querySelectorAll('[data-roll-tag-side]').forEach(b=>b.addEventListener('click',()=>rollTagSide(d,b.dataset.rollTagSide)));d.querySelectorAll('[data-choose-tag]').forEach(b=>b.addEventListener('click',()=>resolveTag(d,b.dataset.chooseTag)));}
  function rollTagSide(d,k){const side=d.querySelector(`[data-tag-side="${k}"]`),trait=side.querySelector('[data-tag-trait]').value,mod=Number(side.querySelector('[data-tag-mod]').value)||0,mode=side.querySelector('[data-tag-mode]').value,h=die(12),f=die(12),advDie=mode==='normal'?0:die(6),adv=mode==='advantage'?advDie:mode==='disadvantage'?-advDie:0,traitMod=currentTrait(k,trait),total=h+f+traitMod+mod+adv,critical=h===f,axis=critical||h>f?'Hope':'Fear';tagDraft.rolls[k]={h,f,total,critical,axis,trait,traitMod,mod,adv};side.querySelector('[data-tag-roll-display]').innerHTML=`<b>${total} ${critical?'CRITICAL':`with ${axis}`}</b><br>Hope ${h} · Fear ${f} · ${trait} ${traitMod>=0?'+':''}${traitMod}${adv?` · ${mode} ${adv>=0?'+':''}${adv}`:''}${mod?` · other ${mod>=0?'+':''}${mod}`:''}`;const ready=Boolean(tagDraft.rolls[activeKey]&&tagDraft.rolls[tagDraft.partner]);d.querySelectorAll('[data-choose-tag]').forEach(b=>b.disabled=!ready);}
  function resolveTag(d,k){const r=tagDraft.rolls[k],partner=tagDraft.partner;if(!r)return;let resourceLine='';if(r.axis==='Hope'){gainHope(1,'Tag Team Roll with Hope');if(r.critical)clearStress(1,'Tag Team critical success');resourceLine=`${name()} gained 1 Hope${r.critical?' and cleared 1 Stress':''}. ${name(partner)} should also gain 1 Hope${r.critical?' and clear 1 Stress':''} on their sheet.`;}else resourceLine='GM gains 2 Fear — one for each PC involved.';d.querySelector('[data-tag-result]').innerHTML=`<div class="tag-result"><strong>Use ${name(k)}’s ${r.total} ${r.critical?'Critical':`with ${r.axis}`}</strong><p>This result applies to both PCs. ${resourceLine}</p>${tagDraft.attack?'<p><b>Attack:</b> if this succeeds, both characters roll their own damage and add the damage totals together.</p>':''}<p>The partner’s resources remain player-owned, so their Hope/Stress change is confirmed on their own sheet rather than silently edited from another player’s browser.</p></div>`;d.querySelectorAll('[data-choose-tag]').forEach(b=>b.disabled=true);}

  function init(){const k=key();if(!k){activeKey=null;state=null;return;}load(k);if(!resourceAPI()||!document.querySelector('#characterSheet .character-sheet-shell')){setTimeout(init,120);return;}render();}
  window.GreywakeTeamwork={get key(){return activeKey;},getState:snapshot,importState,reset:()=>commit({tagUsed:false,tagPartner:null},'Reset Tag Team')};
  const schedule=()=>setTimeout(init,480);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('greywake:resources-changed',()=>{if(activeKey)render();});window.addEventListener('greywake:companion-resources-changed',()=>{if(activeKey)render();});document.addEventListener('DOMContentLoaded',schedule);
})();