(() => {
  const CONFIG={marek:{name:'Marek',tier:1},velmira:{name:'Velmira',tier:1},odie:{name:'Odie',tier:1}};
  const STORAGE_PREFIX='greywake:rest-state:v1:';
  const PARTY_SIZE=3;
  let activeKey=null,state=null,draft=null,observer=null;
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
  const die=sides=>{if(window.crypto?.getRandomValues){const b=new Uint32Array(1);window.crypto.getRandomValues(b);return(b[0]%sides)+1;}return Math.floor(Math.random()*sides)+1;};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));

  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return CONFIG[k]?k:null;}
  function cfg(){return activeKey?CONFIG[activeKey]:null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function resourceAPI(){return activeKey==='marek'?window.GreywakeResources:window.GreywakeCompanion;}
  function resources(){return resourceAPI()?.getState?.()||null;}
  function damageAPI(){return window.GreywakeDamage||null;}

  function baseState(){return{water:null,lastRest:null,restCounter:0,history:[]};}
  function load(k){if(!CONFIG[k])return null;if(activeKey===k&&state)return state;activeKey=k;try{state={...baseState(),...JSON.parse(localStorage.getItem(STORAGE_PREFIX+k)||'null')};}catch(_){state=baseState();}state.water=state.water===null||state.water===undefined?null:clamp(state.water,0,99);state.restCounter=Math.max(0,Number(state.restCounter)||0);state.history=Array.isArray(state.history)?state.history.slice(-12):[];return state;}
  function save(){try{localStorage.setItem(STORAGE_PREFIX+activeKey,JSON.stringify(state));}catch(_){}}
  function snapshot(){return state?{water:state.water===null?null:Number(state.water),lastRest:state.lastRest||null,restCounter:Number(state.restCounter)||0}:null;}
  function commit(next,reason,{history=true}={}){if(!state)return{ok:false};if(history)state.history.push({state:snapshot(),reason,at:Date.now()});state.history=state.history.slice(-12);Object.assign(state,next);state.water=state.water===null?null:clamp(state.water,0,99);save();render();const detail={ok:true,key:activeKey,reason,state:snapshot()};window.dispatchEvent(new CustomEvent('greywake:rest-state-changed',{detail}));return detail;}
  function importState(remote){if(!state||!remote)return;state.water=remote.water===null||remote.water===undefined?null:clamp(remote.water,0,99);state.lastRest=remote.lastRest||null;state.restCounter=Math.max(0,Number(remote.restCounter)||0);save();render();}
  function setWater(value){if(isPreview())return;const v=value===null?null:clamp(value,0,99);commit({water:v},'Set carried Water');}

  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let p=document.getElementById('restPanel');if(!p){p=document.createElement('section');p.id='restPanel';p.className='rest-panel';const damage=document.getElementById('damageHealthPanel');if(damage)damage.insertAdjacentElement('afterend',p);else{const board=identity.querySelector('.pro-resource-board');if(board)board.insertAdjacentElement('afterend',p);else identity.appendChild(p);}}return p;}
  function waterText(){return state.water===null?'Not set':`${state.water} Water`;}
  function renderPanel(){const p=ensurePanel();if(!p)return;const disabled=isPreview()||['dead','retired','death_move','blaze_pending'].includes(window.GreywakeDamage?.getState?.()?.status||'active');p.innerHTML=`<div class="rest-panel-head"><div><span>DOWNTIME</span><strong>Rest & Water</strong><small data-rest-sync-label>${isPreview()?'GM preview · read only':'Live Greywake state'}</small></div><div class="rest-open-buttons"><button type="button" data-rest="short" ${disabled?'disabled':''}>Short Rest</button><button type="button" data-rest="long" ${disabled?'disabled':''}>Long Rest</button></div></div><div class="rest-water"><div class="rest-water-copy"><span>CARRIED WATER</span><strong>${waterText()}</strong><small>Greywake: a Short or Long Rest costs 1 Water per character. Set this when travel supplies are established.</small></div><div class="rest-water-controls"><button type="button" data-water-delta="-1" ${isPreview()||state.water===null||state.water<=0?'disabled':''}>−</button><input data-water-input type="number" min="0" max="99" value="${state.water===null?'':state.water}" placeholder="?" ${isPreview()?'disabled':''}><button type="button" data-water-delta="1" ${isPreview()?'disabled':''}>+</button><button type="button" data-water-set ${isPreview()?'disabled':''}>Set Water</button></div></div><div class="rest-water-status ${state.water===null||state.water===0?'warn':''}">${state.water===null?'Water quantity is deliberately unset because the campaign record does not establish a current carried total.':state.water===0?'No carried Water: Short Rest gives no benefit; Long Rest is reduced to Short-Rest benefits.':'Water is available for a full rest.'}</div>`;
    p.querySelectorAll('[data-rest]').forEach(b=>b.addEventListener('click',()=>openRest(b.dataset.rest)));
    p.querySelector('[data-water-set]')?.addEventListener('click',()=>{const input=p.querySelector('[data-water-input]');if(input?.value==='')return;setWater(Number(input.value));});
    p.querySelectorAll('[data-water-delta]').forEach(b=>b.addEventListener('click',()=>{const delta=Number(b.dataset.waterDelta||0),current=state.water===null?0:state.water;setWater(current+delta);}));
  }

  function ensureDialog(){const host=document.getElementById('characterPageView')||document.body;let d=document.getElementById('restDialog');if(!d){d=document.createElement('dialog');d.id='restDialog';d.className='rest-dialog';host.appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}return d;}
  function makeDraft(type){const useWater=state.water!==null&&state.water>0;return{attempted:type,useWater,confirmNoWater:!useWater,moves:{tend:0,stress:0,armor:0,prepare:0,project:0},targets:{tend:'self',armor:'self'},groupPrepare:false,result:null};}
  function effectiveType(){if(draft.useWater)return draft.attempted;if(draft.attempted==='long')return'short';return'none';}
  function moveTotal(){return Object.values(draft.moves).reduce((a,b)=>a+Number(b||0),0);}
  function moveDefs(type){if(type==='long')return[{id:'tend',name:'Tend to All Wounds',copy:'Clear all marked HP. You can do this to an ally instead.',target:true},{id:'stress',name:'Clear All Stress',copy:'Clear all marked Stress.'},{id:'armor',name:'Repair All Armor',copy:'Clear all marked Armor Slots. You can do this to an ally instead.',target:true},{id:'prepare',name:'Prepare',copy:'Gain 1 Hope; preparing with party members grants 2 Hope each.',prepare:true},{id:'project',name:'Work on a Project',copy:'Establish or continue a project; the GM may call for a progress roll.'}];return[{id:'tend',name:'Tend to Wounds',copy:`Roll 1d4 + Tier (${cfg().tier}) and clear that many HP. You can do this to an ally instead.`,target:true},{id:'stress',name:'Clear Stress',copy:`Roll 1d4 + Tier (${cfg().tier}) and clear that many Stress.`},{id:'armor',name:'Repair Armor',copy:`Roll 1d4 + Tier (${cfg().tier}) and clear that many Armor Slots. You can do this to an ally instead.`,target:true},{id:'prepare',name:'Prepare',copy:'Gain 1 Hope; preparing with party members grants 2 Hope each.',prepare:true}];}
  function moveCard(def){const count=draft.moves[def.id]||0;return `<div class="rest-move-card" data-rest-move-card="${def.id}"><span>DOWNTIME MOVE</span><strong>${esc(def.name)}</strong><p>${esc(def.copy)}</p><div class="rest-move-counter"><button type="button" data-move-delta="-1" data-move="${def.id}" ${count<=0?'disabled':''}>−</button><b>${count}</b><button type="button" data-move-delta="1" data-move="${def.id}" ${moveTotal()>=2?'disabled':''}>+</button></div>${def.target?`<select class="rest-target-select" data-target="${def.id}" ${count?'':'disabled'}><option value="self" ${draft.targets[def.id]==='self'?'selected':''}>Apply to ${cfg().name}</option><option value="ally" ${draft.targets[def.id]==='ally'?'selected':''}>Apply to an ally (show result only)</option></select>`:''}${def.prepare?`<div class="rest-move-extra"><label><input type="checkbox" data-group-prepare ${draft.groupPrepare?'checked':''} ${count?'':'disabled'}> Prepare together with one or more party members (+2 Hope instead of +1)</label></div>`:''}</div>`;}
  function restRuleCopy(){if(draft.useWater)return`Spend 1 Water. ${draft.attempted==='long'?'Use full Long-Rest downtime moves.':'Use normal Short-Rest downtime moves.'}`;if(draft.attempted==='short')return'<strong>No Water:</strong> Greywake Short Rest gives no mechanical benefit.';return'<strong>No Water:</strong> Greywake Long Rest only grants Short-Rest benefits.';}
  function renderDialog(){const d=ensureDialog(),effective=effectiveType(),defs=effective==='none'?[]:moveDefs(effective);const waterAvailable=state.water!==null&&state.water>0;d.innerHTML=`<div class="rest-dialog-shell"><div class="rest-dialog-head"><div><span>${draft.attempted.toUpperCase()} REST · GREYWAKE</span><h2>${cfg().name} rests</h2><p>Daggerheart downtime, with Greywake’s Water cost applied before recovery.</p></div><button class="rest-dialog-close" type="button" data-close>×</button></div><div class="rest-water-choice"><label class="rest-water-option"><input type="radio" name="restWater" value="water" ${draft.useWater?'checked':''} ${waterAvailable?'':'disabled'}><span><b>Spend 1 Water</b><small>${waterAvailable?`${state.water} currently carried · ${state.water-1} after the rest`:'No confirmed Water available'}</small></span></label><label class="rest-water-option"><input type="radio" name="restWater" value="none" ${!draft.useWater?'checked':''}><span><b>Rest without Water</b><small>Apply Greywake’s reduced/no-benefit rule.</small></span></label></div><div class="rest-rule-banner">${restRuleCopy()}</div>${effective!=='none'?`<div class="rest-moves-head"><strong>Choose two downtime moves</strong><span>${moveTotal()} / 2 selected · the same move may be chosen twice</span></div><div class="rest-moves">${defs.map(moveCard).join('')}</div>`:`<div class="rest-result"><span>NO RECOVERY</span><strong>Short Rest without Water</strong><p>No HP, Stress, Armor or Hope recovery is granted.</p></div>`}<button class="rest-complete" type="button" data-complete-rest ${(effective!=='none'&&moveTotal()!==2)?'disabled':''}>Complete ${draft.attempted==='long'?'Long':'Short'} Rest</button><div id="restOutcome"></div></div>`;
    d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());
    d.querySelectorAll('input[name="restWater"]').forEach(r=>r.addEventListener('change',()=>{draft.useWater=r.value==='water';draft.moves={tend:0,stress:0,armor:0,prepare:0,project:0};renderDialog();}));
    d.querySelectorAll('[data-move-delta]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.move,delta=Number(b.dataset.moveDelta||0);draft.moves[id]=clamp((draft.moves[id]||0)+delta,0,2);if(moveTotal()>2)draft.moves[id]-=delta;renderDialog();}));
    d.querySelectorAll('[data-target]').forEach(s=>s.addEventListener('change',()=>{draft.targets[s.dataset.target]=s.value;}));
    d.querySelector('[data-group-prepare]')?.addEventListener('change',e=>{draft.groupPrepare=e.target.checked;});
    d.querySelector('[data-complete-rest]')?.addEventListener('click',completeRest);
  }
  function openRest(type){if(isPreview())return;draft=makeDraft(type);const d=ensureDialog();renderDialog();if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');}

  function clearHP(amount,reason){const api=resourceAPI(),s=resources();if(api&&s)api.setResource?.('hp',Math.max(0,s.hp-amount),reason);}
  function clearAllHP(reason){const api=resourceAPI();api?.setResource?.('hp',0,reason);}
  function clearStress(amount,reason){const api=resourceAPI(),s=resources();if(api&&s)api.setResource?.('stress',Math.max(0,s.stress-amount),reason);}
  function clearAllStress(reason){const api=resourceAPI();api?.setResource?.('stress',0,reason);}
  function gainHope(amount,reason){resourceAPI()?.gainHope?.(amount,reason);}
  function repairArmor(amount){damageAPI()?.repairArmor?.(amount);}
  function repairAllArmor(){damageAPI()?.repairAllArmor?.();}
  function wakeAfterLongRest(){const d=damageAPI()?.getState?.();if(!d||d.status!=='unconscious')return;damageAPI()?.importState?.({...d,status:'active',deathMove:d.deathMove||'avoid'});window.dispatchEvent(new CustomEvent('greywake:damage-changed',{detail:{ok:true,key:activeKey,reason:'Long Rest · regain consciousness',state:damageAPI()?.getState?.()}}));}
  function endRestEffects(attempted,effective){if(activeKey==='odie'&&window.GreywakeCompanion?.setEffect)window.GreywakeCompanion.setEffect('rogueDodge',false,'Rest ends Rogue’s Dodge');if(effective==='long')wakeAfterLongRest();window.dispatchEvent(new CustomEvent('greywake:rest-completed',{detail:{character:activeKey,attempted,effective,waterSpent:draft.useWater?1:0}}));}

  function applyShortMoves(lines){for(const [id,countRaw] of Object.entries(draft.moves)){const count=Number(countRaw)||0;if(!count)continue;if(id==='tend'){const rolls=Array.from({length:count},()=>die(4)+cfg().tier),total=rolls.reduce((a,b)=>a+b,0);if(draft.targets.tend==='self'){clearHP(total,'Short Rest · Tend to Wounds');lines.push(`Tend to Wounds: cleared up to ${total} HP (${rolls.join(' + ')} recovery).`);}else lines.push(`Tend to Wounds for ally: ally may clear ${total} HP (${rolls.join(' + ')} recovery).`);}if(id==='stress'){const rolls=Array.from({length:count},()=>die(4)+cfg().tier),total=rolls.reduce((a,b)=>a+b,0);clearStress(total,'Short Rest · Clear Stress');lines.push(`Clear Stress: cleared up to ${total} Stress (${rolls.join(' + ')} recovery).`);}if(id==='armor'){const rolls=Array.from({length:count},()=>die(4)+cfg().tier),total=rolls.reduce((a,b)=>a+b,0);if(draft.targets.armor==='self'){repairArmor(total);lines.push(`Repair Armor: cleared up to ${total} Armor Slots (${rolls.join(' + ')} recovery).`);}else lines.push(`Repair Armor for ally: ally may clear ${total} Armor Slots (${rolls.join(' + ')} recovery).`);}if(id==='prepare'){const per=draft.groupPrepare?2:1,total=per*count;gainHope(total,'Rest · Prepare');lines.push(`Prepare: gained up to ${total} Hope${draft.groupPrepare?' by preparing together':''}.`);}}}
  function applyLongMoves(lines){for(const [id,countRaw] of Object.entries(draft.moves)){const count=Number(countRaw)||0;if(!count)continue;if(id==='tend'){if(draft.targets.tend==='self'){clearAllHP('Long Rest · Tend to All Wounds');lines.push('Tend to All Wounds: cleared all marked HP.');}else lines.push('Tend to All Wounds for ally: that ally may clear all marked HP.');}if(id==='stress'){clearAllStress('Long Rest · Clear All Stress');lines.push('Clear All Stress: cleared all marked Stress.');}if(id==='armor'){if(draft.targets.armor==='self'){repairAllArmor();lines.push('Repair All Armor: cleared all marked Armor Slots.');}else lines.push('Repair All Armor for ally: that ally may clear all marked Armor Slots.');}if(id==='prepare'){const per=draft.groupPrepare?2:1,total=per*count;gainHope(total,'Long Rest · Prepare');lines.push(`Prepare: gained up to ${total} Hope${draft.groupPrepare?' by preparing together':''}.`);}if(id==='project'){lines.push(`Work on a Project${count>1?' ×'+count:''}: establish or continue the project with the GM; no project progress was invented by the sheet.`);}}}
  function completeRest(){if(isPreview())return;const effective=effectiveType();if(effective!=='none'&&moveTotal()!==2)return;const lines=[];if(effective==='short')applyShortMoves(lines);if(effective==='long')applyLongMoves(lines);const waterSpent=draft.useWater?1:0;if(waterSpent)state.water=Math.max(0,(state.water||0)-1);const fearDie=die(4),fear=draft.attempted==='long'?PARTY_SIZE+fearDie:fearDie;const record={attempted:draft.attempted,effective,waterSpent,at:new Date().toISOString(),gmFear:fear};commit({water:state.water,lastRest:record,restCounter:state.restCounter+1},`${draft.attempted==='long'?'Long':'Short'} Rest completed`);endRestEffects(draft.attempted,effective);const out=document.getElementById('restOutcome');if(out)out.innerHTML=`<div class="rest-result"><span>REST COMPLETE</span><strong>${draft.attempted==='long'?'Long':'Short'} Rest${effective!==draft.attempted?` · ${effective==='short'?'Short-Rest benefits only':'no recovery'}`:''}</strong><p>${waterSpent?`1 Water spent · ${state.water} Water remains.`:'No Water spent.'} GM Fear from this rest: <b>${fear}</b>${draft.attempted==='long'?` (${PARTY_SIZE} PCs + d4 result ${fearDie})`:` (d4 result ${fearDie})`}.</p>${lines.length?`<ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No recovery benefits were applied.</p>'}<button type="button" data-finish-rest>Return to sheet</button></div>`;out?.querySelector('[data-finish-rest]')?.addEventListener('click',()=>document.getElementById('restDialog')?.close());}

  function render(){if(!activeKey||!state)return;renderPanel();document.body.classList.toggle('rest-readonly',isPreview());}
  function init(){const k=key();if(!k){activeKey=null;state=null;observer?.disconnect();return;}load(k);if(!resourceAPI()||!window.GreywakeDamage){setTimeout(init,120);return;}render();observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>{if(activeKey&&!document.getElementById('restPanel'))renderPanel();}));observer.observe(document.getElementById('characterSheet')||document.body,{childList:true,subtree:true});}

  window.GreywakeRest={get key(){return activeKey;},getState:snapshot,importState,setWater,openShort:()=>openRest('short'),openLong:()=>openRest('long'),render};
  const schedule=()=>setTimeout(init,210);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);document.addEventListener('DOMContentLoaded',schedule);
})();