(() => {
  function loadConditions(){
    if(!document.querySelector('link[data-greywake-conditions]')){const l=document.createElement('link');l.rel='stylesheet';l.href='conditions-system.css?v=conditions1';l.dataset.greywakeConditions='true';document.head.appendChild(l);}
    if(window.GreywakeConditions||document.querySelector('script[data-greywake-conditions-system]'))return;
    const s=document.createElement('script');s.src='conditions-system.js?v=conditions1';s.async=false;s.dataset.greywakeConditionsSystem='true';s.addEventListener('load',()=>{if(document.querySelector('script[data-greywake-conditions-sync]'))return;const q=document.createElement('script');q.src='conditions-sync.js?v=conditions1';q.async=false;q.dataset.greywakeConditionsSync='true';document.head.appendChild(q);});document.head.appendChild(s);
  }
  loadConditions();

  const API_URL='https://tmqxxgzqiccclcjagdsh.supabase.co/functions/v1/player-goals?include_system=1';
  const API_KEY='sb_publishable_zML4qGtgQgMALEXFJn501w_1imfz8wl';
  const SYSTEM_KIND='system_rest_state';
  const POLL_MS=5000;
  let activeKey=null,systemGoalId=null,lastServerMessageId=0,remoteRevision=0,applying=false,pushPending=false,pushTimer=null,pollTimer=null,initialized=false;
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return['marek','velmira','odie'].includes(k)?k:null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function identity(){const user=window.GreywakePlayer,character=key(),code=String(user?.code||character||'').toUpperCase();return{character,code};}
  async function request(method='GET',body=null){const auth=identity();if(!auth.character||!auth.code)throw new Error('Greywake rest sync identity is unavailable.');const res=await fetch(API_URL,{method,headers:{apikey:API_KEY,'Content-Type':'application/json','x-greywake-character':auth.character,'x-greywake-code':auth.code},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Greywake rest state could not sync.');return data;}
  function localState(){const s=window.GreywakeRest?.getState?.();if(!s)return null;return{water:s.water===null?null:Number(s.water),lastRest:s.lastRest||null,restCounter:Number(s.restCounter)||0};}
  function valid(v){return Boolean(v&&Number(v.v)===1&&(v.water===null||(Number.isInteger(Number(v.water))&&Number(v.water)>=0))&&Number.isInteger(Number(v.restCounter||0))&&Number(v.restCounter||0)>=0);}
  function same(a,b){return a&&b&&(a.water===null?b.water===null:Number(a.water)===Number(b.water))&&Number(a.restCounter||0)===Number(b.restCounter||0)&&JSON.stringify(a.lastRest||null)===JSON.stringify(b.lastRest||null);}
  function parseLatest(bundle){const goals=Array.isArray(bundle?.goals)?bundle.goals:[],messages=Array.isArray(bundle?.messages)?bundle.messages:[];const g=goals.find(x=>x?.character_slug===activeKey&&x?.source_kind===SYSTEM_KIND&&x?.source_key===activeKey);if(!g)return null;systemGoalId=Number(g.id);const candidates=messages.filter(m=>Number(m.goal_id)===systemGoalId).sort((a,b)=>Number(b.id)-Number(a.id));for(const m of candidates){try{const p=JSON.parse(m.message_text);if(valid(p))return{...p,messageId:Number(m.id)};}catch(_){}}return null;}
  function label(text,error=false){const n=document.querySelector('#restPanel [data-rest-sync-label]');if(n){n.textContent=text;n.classList.toggle('rest-sync-error',error);}}
  function applyRemote(remote){const api=window.GreywakeRest,current=localState();if(!api||!current||!valid(remote)||same(current,remote))return;applying=true;try{api.importState(remote);}finally{applying=false;}}
  async function pull({initial=false}={}){if(!activeKey||!window.GreywakeRest)return;if(pushPending&&!isPreview()){await push('Reconnect pending rest state');if(pushPending)return;}try{const remote=parseLatest(await request('GET'));if(!remote)throw new Error('Rest sync record missing.');remoteRevision=Math.max(remoteRevision,Number(remote.revision)||0);const local=localState(),untouched=remote.source==='initial_import'&&Number(remote.revision)<=1;if(initial&&!isPreview()&&untouched&&local&&!same(local,remote)){lastServerMessageId=Number(remote.messageId)||0;await push('First rest sync','local_migration');return;}if(Number(remote.messageId)>lastServerMessageId){applyRemote(remote);lastServerMessageId=Number(remote.messageId)||lastServerMessageId;}label(isPreview()?'GM preview · live Water/rest state · read only':'Water & rests synced across devices');}catch(error){label('Local rest state · sync will retry',true);console.warn('Greywake rest sync pull failed:',error);}}
  async function push(reason='Rest update',source='client'){if(!activeKey||isPreview()||applying)return;const s=localState();if(!s)return;try{if(!systemGoalId){const remote=parseLatest(await request('GET'));if(!remote||!systemGoalId)throw new Error('Rest sync record unavailable.');remoteRevision=Math.max(remoteRevision,Number(remote.revision)||0);lastServerMessageId=Math.max(lastServerMessageId,Number(remote.messageId)||0);}const payload={v:1,...s,revision:remoteRevision+1,source,reason:String(reason||'Rest update').slice(0,120),at:new Date().toISOString()};const result=await request('POST',{goal_id:systemGoalId,message:JSON.stringify(payload),kind:'reply'});remoteRevision=payload.revision;if(result?.message?.id)lastServerMessageId=Number(result.message.id);pushPending=false;label('Water & rests synced across devices');}catch(error){pushPending=true;label('Local rest change waiting to sync',true);console.warn('Greywake rest sync push failed:',error);}}
  function schedulePush(event){if(applying||isPreview()||!activeKey)return;pushPending=true;clearTimeout(pushTimer);pushTimer=setTimeout(()=>push(event?.detail?.reason||'Rest update'),450);}
  function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&activeKey)pull();},POLL_MS);}
  async function init(){const k=key();if(!k){activeKey=null;clearInterval(pollTimer);return;}if(activeKey!==k){activeKey=k;systemGoalId=null;lastServerMessageId=0;remoteRevision=0;pushPending=false;initialized=false;}if(!window.GreywakeRest||window.GreywakeRest.key!==k){setTimeout(init,120);return;}startPolling();await pull({initial:true});initialized=true;}
  window.addEventListener('greywake:rest-state-changed',schedulePush);window.addEventListener('greywake:player-ready',()=>setTimeout(init,250));window.addEventListener('focus',()=>{if(initialized&&activeKey)pull();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&initialized&&activeKey)pull();});document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));
})();