(() => {
  const PREFIX='greywake:progression:v1:';
  const RUNTIME_PREFIX='greywake:progression-runtime:v1:';
  const BASE={
    marek:{level:1,evasion:12,proficiency:1,hp:6,stress:7,traits:{Agility:1,Strength:0,Finesse:1,Instinct:2,Presence:-1,Knowledge:0},experiences:{'Body Language':2,'Let Me Try Something':2}},
    velmira:{level:1,evasion:11,proficiency:1,hp:5,stress:7,traits:{Agility:-1,Strength:0,Finesse:0,Instinct:1,Presence:1,Knowledge:2},experiences:{'Friend to All':2,'Fake It Till You Make It':2}},
    odie:{level:1,evasion:13,proficiency:1,hp:6,stress:6,traits:{Agility:1,Strength:1,Finesse:2,Instinct:0,Presence:-1,Knowledge:0},experiences:{Repair:3,Scavenger:2}}
  };
  let activeKey=null,observer=null,rendering=false;
  const wrapped=new Set();
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return BASE[k]?k:null;}
  function defaultState(){return{v:1,level:1,proficiency:1,traitBonuses:{},markedTraits:[],hpBonus:0,stressBonus:0,evasionBonus:0,experienceBonuses:{},addedExperiences:[],addedDomainCards:[],advancementMarks:[]};}
  function state(k=activeKey){if(!k)return defaultState();try{return{...defaultState(),...JSON.parse(localStorage.getItem(PREFIX+k)||'null')};}catch(_){return defaultState();}}
  function saveState(k,s){try{localStorage.setItem(PREFIX+k,JSON.stringify({...defaultState(),...s}));}catch(_){}}
  function runtime(k=activeKey){try{return{hpExtra:0,stressExtra:0,...JSON.parse(localStorage.getItem(RUNTIME_PREFIX+k)||'null')};}catch(_){return{hpExtra:0,stressExtra:0};}}
  function saveRuntime(k,r){try{localStorage.setItem(RUNTIME_PREFIX+k,JSON.stringify(r));}catch(_){}}
  function isActive(k=activeKey){return Boolean(k&&Number(state(k).level)>1);}
  function progression(){return state(activeKey);}
  function combinedExp(name){const p=progression(),base=BASE[activeKey]?.experiences?.[name]??p.addedExperiences.find(x=>x.name===name)?.bonus??0;return Number(base)+(Number(p.experienceBonuses?.[name])||0);}

  function wrapResources(){const k=key();if(!k||!isActive(k))return;const api=k==='marek'?window.GreywakeResources:window.GreywakeCompanion;if(!api||wrapped.has(api)||api.__progressionWrapped)return;const baseGet=api.getState?.bind(api),baseSet=api.setResource?.bind(api),baseMark=api.markStress?.bind(api),baseClear=api.clearStress?.bind(api),baseImport=api.importState?.bind(api),baseRender=api.render?.bind(api);if(!baseGet||!baseSet)return;
    function merged(){const b=baseGet(),p=state(k),r=runtime(k),maxHP=Number(b.maxHP)+(Number(p.hpBonus)||0),maxStress=Number(b.maxStress)+(Number(p.stressBonus)||0),hp=clamp(Number(b.hp)+(Number(r.hpExtra)||0),0,maxHP),stress=clamp(Number(b.stress)+(Number(r.stressExtra)||0),0,maxStress);return{...b,hp,maxHP,stress,maxStress,vulnerable:stress>=maxStress};}
    function dispatch(reason){const event=k==='marek'?'greywake:resources-changed':'greywake:companion-resources-changed';window.dispatchEvent(new CustomEvent(event,{detail:{ok:true,key:k,reason,after:merged(),progression:true}}));}
    function setCombined(resource,value,reason='Manual adjustment'){if(!['hp','stress'].includes(resource))return baseSet(resource,value,reason);const b=baseGet(),p=state(k),r=runtime(k),baseMax=resource==='hp'?Number(b.maxHP):Number(b.maxStress),bonus=resource==='hp'?Number(p.hpBonus||0):Number(p.stressBonus||0),max=baseMax+bonus,target=clamp(value,0,max),baseValue=Math.min(target,baseMax),extra=Math.max(0,target-baseMax);if(resource==='hp')r.hpExtra=extra;else r.stressExtra=extra;saveRuntime(k,r);const result=baseSet(resource,baseValue,reason);dispatch(reason);setTimeout(renderProgressionBoard,0);return{...(result||{}),ok:result?.ok!==false,after:merged(),resource};}
    function markStress(n=1,options={}){n=Math.max(0,Number(n)||0);const s=merged(),free=s.maxStress-s.stress,reason=options.reason||'Mark Stress';if(options.cost&&free<n)return{ok:false,message:`${BASE[k].name||k} has only ${free} free Stress slot${free===1?'':'s'}.`,after:s};const mark=Math.min(n,free);setCombined('stress',s.stress+mark,reason);if(n>free&&!options.cost)setCombined('hp',s.hp+1,`${reason} · Stress overflow`);return{ok:true,after:merged(),overflow:n>free};}
    function clearStress(n=1,reason='Clear Stress'){const s=merged();return setCombined('stress',Math.max(0,s.stress-Math.max(0,Number(n)||0)),reason);}
    api.getState=merged;api.setResource=setCombined;api.markStress=markStress;api.clearStress=clearStress;api.canMarkStress=n=>merged().stress+Number(n||0)<=merged().maxStress;
    if(baseImport)api.importState=remote=>{if(!remote)return;const p=state(k),b=baseGet(),r=runtime(k),hpTarget=clamp(remote.hp,0,Number(b.maxHP)+Number(p.hpBonus||0)),stressTarget=clamp(remote.stress,0,Number(b.maxStress)+Number(p.stressBonus||0));r.hpExtra=Math.max(0,hpTarget-Number(b.maxHP));r.stressExtra=Math.max(0,stressTarget-Number(b.maxStress));saveRuntime(k,r);baseImport({...remote,hp:Math.min(hpTarget,Number(b.maxHP)),stress:Math.min(stressTarget,Number(b.maxStress)),maxHP:b.maxHP,maxStress:b.maxStress});setTimeout(renderProgressionBoard,0);};
    if(baseRender)api.render=()=>{baseRender();setTimeout(()=>{renderProgressionBoard();applyStats();},0);};
    api.__progressionWrapped=true;wrapped.add(api);dispatch('Level progression capacity active');
  }

  function resourceAPI(){return activeKey==='marek'?window.GreywakeResources:window.GreywakeCompanion;}
  function resourceName(r){return r==='hp'?'HP':r==='stress'?'Stress':'Hope';}
  function progressionPips(resource,current,max){return Array.from({length:max},(_,i)=>`<button type="button" class="live-resource-pip ${i<current?'filled':''}" data-prog-resource="${resource}" data-value="${i+1}" aria-pressed="${i<current?'true':'false'}"></button>`).join('');}
  function row(resource,label,current,max,sub){return`<div class="live-resource-row live-resource-${resource}"><div class="live-resource-copy"><span>${label}</span><strong>${current}<small> / ${max}</small></strong><em>${sub}</em></div><div class="live-resource-controls"><button type="button" data-prog-adjust="${resource}" data-delta="-1">−</button><div class="live-resource-pips">${progressionPips(resource,current,max)}</div><button type="button" data-prog-adjust="${resource}" data-delta="1">+</button></div></div>`;}
  function renderProgressionBoard(){if(rendering||!isActive()||!(progression().hpBonus||progression().stressBonus))return;const api=resourceAPI(),s=api?.getState?.(),board=document.querySelector('#characterSheet .pro-resource-board');if(!s||!board)return;const sig=[s.hope,s.maxHope,s.stress,s.maxStress,s.hp,s.maxHP].join('|');if(board.dataset.progressionSignature===sig)return;rendering=true;board.dataset.progressionSignature=sig;board.classList.add('live-resource-board','progression-resource-board');board.innerHTML=`<div class="pro-board-title"><span>LIVE FIELD CONDITION</span><small>Level ${progression().level} · expanded capacity</small></div>${row('hope','Hope',s.hope,s.maxHope,'Experiences and Hope features')}${row('stress','Stress',s.stress,s.maxStress,'marked slots')}${row('hp','HP',s.hp,s.maxHP,'marked Hit Points')}<div class="live-resource-foot"><span class="live-resource-condition ${s.vulnerable?'active':''}">${s.vulnerable?'VULNERABLE · last Stress marked':'Stable · Stress slots remain'}</span><span>Permanent slots from Level Up are included.</span></div>`;board.querySelectorAll('[data-prog-adjust]').forEach(b=>b.addEventListener('click',()=>{const r=b.dataset.progAdjust,d=Number(b.dataset.delta),now=api.getState();if(r==='hope')d>0?api.gainHope?.(1,'Manual Hope adjustment'):api.spendHope?.(Math.min(1,now.hope),'Manual Hope adjustment');else api.setResource(r,now[r]+d,`Manual ${resourceName(r)} adjustment`);}));board.querySelectorAll('[data-prog-resource]').forEach(b=>b.addEventListener('click',()=>{const r=b.dataset.progResource,v=Number(b.dataset.value),now=api.getState(),cur=now[r];api.setResource(r,cur===v?v-1:v,`Set ${resourceName(r)}`);}));rendering=false;}

  function statNode(label){return[...document.querySelectorAll('#characterSheet .character-stat')].find(n=>n.querySelector('span')?.textContent.trim().toLowerCase()===label.toLowerCase())||null;}
  function traitCard(name){return[...document.querySelectorAll('#characterSheet .sheet-grid.traits .sheet-card')].find(c=>c.querySelector('h4')?.textContent.trim()===name)||null;}
  function fmt(n){return n>0?`+${n}`:n<0?`−${Math.abs(n)}`:'0';}
  function applyStats(){if(!activeKey||!isActive())return;const p=progression(),base=BASE[activeKey];const level=statNode('Level'),prof=statNode('Proficiency');if(level?.querySelector('strong'))level.querySelector('strong').textContent=String(p.level);if(prof?.querySelector('strong'))prof.querySelector('strong').textContent=String(p.proficiency||p.level);
    const beast=activeKey==='marek'&&document.body.classList.contains('marek-beastform-active');if(!beast){for(const [name,val] of Object.entries(base.traits)){const c=traitCard(name),v=c?.querySelector('.sheet-value');if(v)v.textContent=fmt(Number(val)+(Number(p.traitBonuses?.[name])||0));}const ev=statNode('Evasion')?.querySelector('strong');if(ev){const dodge=activeKey==='odie'&&Boolean(window.GreywakeCompanion?.getState?.()?.effects?.rogueDodge);ev.textContent=String(base.evasion+Number(p.evasionBonus||0)+(dodge?2:0));}}
    applyExperiences();applyDomainCards();renderProgressionBoard();}
  function experienceGroup(){return[...document.querySelectorAll('#characterSheet .sheet-group')].find(g=>g.querySelector('.sheet-group-head h3')?.textContent.trim()==='Experiences')||null;}
  function applyExperiences(){const p=progression(),g=experienceGroup();if(!g)return;for(const card of g.querySelectorAll('.sheet-card')){const name=card.querySelector('h4')?.textContent.trim();if(!name)continue;const base=BASE[activeKey].experiences[name];if(base!==undefined||p.addedExperiences.some(x=>x.name===name)){const v=card.querySelector('.sheet-value');if(v)v.textContent=fmt(combinedExp(name));}}
    const grid=g.querySelector('.sheet-grid');for(const ex of p.addedExperiences){if([...g.querySelectorAll('h4')].some(h=>h.textContent.trim()===ex.name))continue;const d=document.createElement('details');d.className='sheet-card personal-card progression-experience-card';d.innerHTML=`<summary><h4>${ex.name.replace(/[&<>]/g,'')}</h4><span class="sheet-value">+${combinedExp(ex.name)}</span></summary><div class="sheet-card-body"><p>Experience gained at level ${p.level}. Spend a Hope when it genuinely applies to an action roll.</p></div>`;grid?.appendChild(d);}
    enhanceCompanionExperienceRollers();}
  function enhanceCompanionExperienceRollers(){if(activeKey==='marek')return;const p=progression();document.querySelectorAll('#companionActionsPanel .action-roll-experiences').forEach(fs=>{const existing=new Set();fs.querySelectorAll('label').forEach(label=>{const name=label.querySelector('b')?.textContent.trim();if(!name)return;existing.add(name);const bonus=combinedExp(name),input=label.querySelector('[data-comp-exp]');if(input)input.dataset.bonus=String(bonus);const small=label.querySelector('small');if(small)small.textContent=`+${bonus}`;});for(const ex of p.addedExperiences){if(existing.has(ex.name))continue;const label=document.createElement('label');label.innerHTML=`<input type="checkbox" data-comp-exp="progression-${existing.size}" data-bonus="${combinedExp(ex.name)}"><span><b>${ex.name.replace(/[&<>]/g,'')}</b><small>+${combinedExp(ex.name)}</small></span>`;fs.appendChild(label);}});}
  function applyDomainCards(){const api=window.GreywakeDomains,p=progression();if(!api||api.key!==activeKey)return;for(const c of p.addedDomainCards||[])api.addCard?.(c);}
  function observe(){observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>{if(activeKey&&isActive()){applyStats();}}));observer.observe(document.getElementById('characterSheet')||document.body,{childList:true,subtree:true,characterData:true});}
  function init(){const k=key();if(!k){activeKey=null;observer?.disconnect();return;}activeKey=k;if(!isActive())return;wrapResources();applyStats();observe();setTimeout(()=>{wrapResources();applyStats();},250);}
  function importProgression(k,remote){saveState(k,remote);if(k===key()&&Number(remote.level)!==Number(progression().level))location.reload();else if(k===key()){activeKey=k;applyStats();}}
  window.GreywakeProgression={get key(){return activeKey;},getState:()=>state(activeKey),getLevel:()=>Number(state(activeKey).level)||1,getProficiency:()=>Number(state(activeKey).proficiency)||1,thresholdBonus:()=>Math.max(0,(Number(state(activeKey).level)||1)-1),domainCards:()=>[...(state(activeKey).addedDomainCards||[])],importProgression,apply:()=>{activeKey=key();wrapResources();applyStats();}};
  const schedule=()=>setTimeout(init,70);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('greywake:progression-changed',()=>location.reload());window.addEventListener('greywake:resources-changed',()=>{if(activeKey&&isActive())setTimeout(applyStats,0);});window.addEventListener('greywake:companion-resources-changed',()=>{if(activeKey&&isActive())setTimeout(applyStats,0);});document.addEventListener('DOMContentLoaded',schedule);
})();