(() => {
  const CONFIG={
    marek:{name:'Marek',cards:[
      {id:'natures-tongue',name:'Nature’s Tongue',domain:'Sage',type:'Ability',recall:0,actions:['Nature’s Tongue']},
      {id:'wall-walk',name:'Wall Walk',domain:'Arcana',type:'Spell',recall:1,actions:['Wall Walk']}
    ]},
    velmira:{name:'Velmira',cards:[
      {id:'mending-touch',name:'Mending Touch',domain:'Splendor',type:'Spell',recall:1,actions:['Mending Touch']},
      {id:'reassurance',name:'Reassurance',domain:'Splendor',type:'Ability',recall:0,actions:['Reassurance']},
      {id:'book-of-ava',name:'Book of Ava',domain:'Codex',type:'Grimoire',recall:2,actions:['Power Push','Tava’s Armor','Dust Spike']}
    ]},
    odie:{name:'Odie',cards:[
      {id:'pick-and-pull',name:'Pick and Pull',domain:'Midnight',type:'Ability',recall:0,actions:['Pick and Pull']},
      {id:'rain-of-blades',name:'Rain of Blades',domain:'Midnight',type:'Spell',recall:1,actions:['Rain of Blades']}
    ]}
  };
  const PREFIX='greywake:domain-state:v1:';
  const MAX_LOADOUT=5;
  let activeKey=null,state=null,restMode=false,observer=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
  function key(){const k=String(window.GreywakePlayer?.character||document.body.dataset.character||'').toLowerCase();return CONFIG[k]?k:null;}
  function cfg(){return CONFIG[activeKey]||null;}
  function isPreview(){return document.body.dataset.gmPreview==='true';}
  function resourceAPI(){return activeKey==='marek'?window.GreywakeResources:window.GreywakeCompanion;}
  function card(id){return cfg()?.cards.find(c=>c.id===id)||null;}
  function base(k){return{loadout:CONFIG[k].cards.map(c=>c.id),vault:[]};}
  function normalise(s){const ids=new Set(cfg().cards.map(c=>c.id));const load=[...new Set((s?.loadout||[]).filter(id=>ids.has(id)))].slice(0,MAX_LOADOUT);const vault=[...new Set((s?.vault||[]).filter(id=>ids.has(id)&&!load.includes(id)))];for(const c of cfg().cards)if(!load.includes(c.id)&&!vault.includes(c.id)){if(load.length<MAX_LOADOUT)load.push(c.id);else vault.push(c.id);}return{loadout:load,vault};}
  function load(k){if(!CONFIG[k])return null;activeKey=k;let stored=null;try{stored=JSON.parse(localStorage.getItem(PREFIX+k)||'null');}catch(_){}state=normalise(stored||base(k));save();return state;}
  function save(){try{localStorage.setItem(PREFIX+activeKey,JSON.stringify(state));}catch(_){}}
  function snapshot(){return state?{loadout:[...state.loadout],vault:[...state.vault]}:null;}
  function commit(next,reason){state=normalise({...state,...next});save();render();window.dispatchEvent(new CustomEvent('greywake:domain-state-changed',{detail:{ok:true,key:activeKey,reason,state:snapshot()}}));return{ok:true};}
  function importState(remote){if(!remote)return;state=normalise(remote);save();render();}
  function setRestMode(value){restMode=Boolean(value);render();}
  function markRecallStress(amount,name){amount=Number(amount)||0;if(amount<=0)return{ok:true};const api=resourceAPI();const rs=api?.getState?.();if(!api||!rs)return{ok:false};if(Number(rs.maxStress)-Number(rs.stress)<amount){alert(`${cfg().name} does not have ${amount} free Stress slot${amount===1?'':'s'} to recall ${name}.`);return{ok:false};}const r=api.markStress?.(amount,{reason:`Recall ${name}`,cost:true});return r?.ok===false?{ok:false}:{ok:true};}
  function moveToVault(id){if(!restMode||isPreview())return;commit({loadout:state.loadout.filter(x=>x!==id),vault:[...state.vault,id]},`Rest swap · ${card(id)?.name} to Vault`);}
  function recallToLoadout(id,outgoing=null){if(isPreview())return;const incoming=card(id);if(!incoming||!state.vault.includes(id))return;if(state.loadout.length>=MAX_LOADOUT&&!outgoing){openManager(id);return;}if(!restMode){const paid=markRecallStress(incoming.recall,incoming.name);if(!paid.ok)return;}let loadout=state.loadout.filter(x=>x!==outgoing);let vault=state.vault.filter(x=>x!==id);if(outgoing)vault.push(outgoing);loadout.push(id);commit({loadout,vault},`${restMode?'Rest swap':'Recall'} · ${incoming.name}`);}
  function addCard(def,{toVault=false}={}){if(!def?.id||card(def.id))return false;cfg().cards.push(def);if(toVault||state.loadout.length>=MAX_LOADOUT)state.vault.push(def.id);else state.loadout.push(def.id);commit(state,`Added domain card · ${def.name||def.id}`);return true;}

  function ensurePanel(){const identity=document.querySelector('#characterSheet .character-sheet-identity');if(!identity)return null;let p=document.getElementById('domainManager');if(!p){p=document.createElement('section');p.id='domainManager';p.className='domain-manager';const conditions=document.getElementById('conditionsPanel'),rest=document.getElementById('restPanel'),damage=document.getElementById('damageHealthPanel');(conditions||rest||damage||identity).insertAdjacentElement(conditions||rest||damage?'afterend':'beforeend',p);}return p;}
  function renderPanel(){const p=ensurePanel();if(!p)return;p.innerHTML=`<div class="domain-manager-head"><div><span>DOMAIN CARDS</span><strong>Loadout & Vault</strong><small data-domain-sync-label>${isPreview()?'GM preview · read only':'Active cards are usable in play'}</small></div><button type="button" data-manage-domains ${isPreview()?'disabled':''}>Manage Cards</button></div><div class="domain-summary"><div><strong>${state.loadout.length} / ${MAX_LOADOUT}</strong><small>active Loadout</small></div><div><strong>${state.vault.length}</strong><small>inactive in Vault</small></div></div>${restMode?'<div class="domain-rest-window"><strong>REST SWAP WINDOW</strong> · Cards may move between Loadout and Vault without paying Recall Cost before downtime moves.</div>':''}<div class="domain-rule-note"><strong>Current level:</strong> all of this character’s known domain cards fit in the Loadout, so the Vault is empty. At six or more cards, inactive cards live in the Vault. Outside a rest, recalling a Vault card marks Stress equal to that card’s Recall Cost.</div>`;p.querySelector('[data-manage-domains]')?.addEventListener('click',()=>openManager());}
  function cardMarkup(id,where,pending){const c=card(id);if(!c)return'';let action='';if(where==='loadout')action=restMode?`<button type="button" data-to-vault="${c.id}">Move to Vault</button>`:'';else{const disabled=state.loadout.length>=MAX_LOADOUT&&!pending;action=`<button type="button" data-recall="${c.id}" ${disabled?'':' '}>${restMode?'Add to Loadout':`Recall · ${c.recall} Stress`}</button>`;}return `<div class="domain-card-ui ${where==='vault'?'inactive':''}"><span>${esc(c.domain.toUpperCase())} · ${esc(c.type.toUpperCase())}</span><strong>${esc(c.name)}</strong><em>Recall Cost ${c.recall}</em>${action}</div>`;}
  function ensureDialog(){let d=document.getElementById('domainDialog');if(!d){d=document.createElement('dialog');d.id='domainDialog';d.className='domain-dialog';(document.getElementById('characterPageView')||document.body).appendChild(d);d.addEventListener('click',e=>{if(e.target===d)d.close();});}return d;}
  function openManager(pendingRecall=null){if(isPreview())return;const d=ensureDialog();const incoming=pendingRecall?card(pendingRecall):null;const outgoingOptions=incoming&&state.loadout.length>=MAX_LOADOUT?`<div class="domain-rule-note"><strong>${esc(incoming.name)} needs a slot.</strong> Choose an active card to move to the Vault.</div>${state.loadout.map(id=>`<button type="button" data-swap-out="${id}" style="width:100%;margin-top:.4rem;min-height:38px">Vault ${esc(card(id)?.name)}</button>`).join('')}`:'';d.innerHTML=`<div class="domain-dialog-shell"><div class="domain-dialog-head"><div><span>DOMAIN MANAGEMENT</span><h2>${cfg().name} · Loadout & Vault</h2><p>${restMode?'Rest swap: no Recall Stress.':'Outside a rest, bringing a card from the Vault into the Loadout marks Stress equal to its Recall Cost.'}</p></div><button class="domain-dialog-close" type="button" data-close>×</button></div>${outgoingOptions||`<div class="domain-columns"><section class="domain-column"><div class="domain-column-head"><span>ACTIVE</span><strong>Loadout ${state.loadout.length}/${MAX_LOADOUT}</strong></div><div class="domain-card-list">${state.loadout.length?state.loadout.map(id=>cardMarkup(id,'loadout')).join(''):'<div class="domain-empty">No active domain cards.</div>'}</div></section><section class="domain-column"><div class="domain-column-head"><span>INACTIVE</span><strong>Vault ${state.vault.length}</strong></div><div class="domain-card-list">${state.vault.length?state.vault.map(id=>cardMarkup(id,'vault')).join(''):'<div class="domain-empty">Vault empty at this level.</div>'}</div></section></div>`}<div class="domain-rule-note">A maximum of five domain cards can be active. Subclass, ancestry and community cards do not count toward this limit.</div></div>`;d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());d.querySelectorAll('[data-to-vault]').forEach(b=>b.addEventListener('click',()=>{moveToVault(b.dataset.toVault);openManager();}));d.querySelectorAll('[data-recall]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.recall;if(state.loadout.length>=MAX_LOADOUT)openManager(id);else{recallToLoadout(id);openManager();}}));d.querySelectorAll('[data-swap-out]').forEach(b=>b.addEventListener('click',()=>{recallToLoadout(pendingRecall,b.dataset.swapOut);openManager();}));if(typeof d.showModal==='function'&&!d.open)d.showModal();else d.setAttribute('open','');}

  function titleOf(node){return node.querySelector('strong')?.textContent.trim()||node.querySelector('h3')?.textContent.trim()||'';}
  function applyAvailability(){const inactive=new Set(state.vault.flatMap(id=>card(id)?.actions||[]));const selectors=['#activeActionsPanel .active-action-card','#companionActionsPanel .active-action-card'];for(const sel of selectors)document.querySelectorAll(sel).forEach(n=>{const title=titleOf(n),off=inactive.has(title);n.classList.toggle('domain-card-vaulted',off);if(off){if(!n.disabled)n.dataset.domainDisabled='true';n.disabled=true;n.title='Domain card is in the Vault.';}else if(n.dataset.domainDisabled==='true'){n.disabled=false;delete n.dataset.domainDisabled;n.removeAttribute('title');}});document.querySelectorAll('#characterSheet .sheet-group').forEach(group=>{if(group.querySelector('.sheet-group-head h3')?.textContent.trim()!=='Domain cards')return;group.querySelectorAll('.sheet-card').forEach(n=>{const off=inactive.has(n.querySelector('h4')?.textContent.trim());n.classList.toggle('domain-card-vaulted',off);});});}
  function injectRestButton(){const d=document.getElementById('restDialog');if(!d?.open)return;restMode=true;let row=d.querySelector('.rest-domain-swap');if(!row){row=document.createElement('div');row.className='rest-domain-swap';row.innerHTML=`<span><strong>Domain Loadout:</strong> swap cards before choosing downtime moves.</span><button type="button">Manage Loadout</button>`;const banner=d.querySelector('.rest-rule-banner');banner?.insertAdjacentElement('afterend',row);row.querySelector('button')?.addEventListener('click',()=>{const picked=[...d.querySelectorAll('.rest-move-counter b')].some(b=>Number(b.textContent)>0);if(picked){alert('Domain cards must be swapped before choosing downtime moves. Set the downtime move counters back to 0 first.');return;}openManager();});}}
  function render(){if(!state)return;renderPanel();applyAvailability();injectRestButton();}
  function watch(){observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(()=>{if(activeKey){applyAvailability();injectRestButton();if(!document.getElementById('domainManager'))renderPanel();}}));observer.observe(document.body,{childList:true,subtree:true});}
  function init(){const k=key();if(!k){activeKey=null;state=null;observer?.disconnect();return;}load(k);if(!document.querySelector('#characterSheet .character-sheet-shell'))return;render();watch();}
  document.addEventListener('click',e=>{if(e.target.closest('#restPanel [data-rest]')){restMode=true;setTimeout(render,0);}},true);
  document.addEventListener('close',e=>{if(e.target?.id==='restDialog'){restMode=false;render();}},true);
  window.addEventListener('greywake:rest-completed',()=>{restMode=false;render();});
  window.GreywakeDomains={get key(){return activeKey;},getState:snapshot,importState,setRestMode,addCard,isActive:id=>Boolean(state?.loadout.includes(id)),open:openManager,render};
  const schedule=()=>setTimeout(init,300);window.addEventListener('greywake:player-ready',schedule);window.addEventListener('greywake:sheet-enhanced',schedule);window.addEventListener('hashchange',schedule);document.addEventListener('DOMContentLoaded',schedule);
})();