import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={window:{}};vm.createContext(context);vm.runInContext(readFileSync(new URL('../catch-up.js',import.meta.url),'utf8'),context);
const {fresh,scan}=context.window.GreywakeCatchupModel;
const one={id:'hollow',title:'Stone-Lip Hollow',sections:['The survivors are sheltered here.'],summary:'The survivors are sheltered here.',route:'#/record/Stone-Lip%20Hollow',image:'assets/hollow.webp'};
let state=fresh();scan(state,'records',[one],'2026-10-02T11:00:00Z');
assert.equal(Object.keys(state.pending).length,0,'First visit establishes baseline rather than calling everything new');
state=JSON.parse(JSON.stringify(state));
const revised={...one,sections:[...one.sections,'The rope has been repaired.']};scan(state,'records',[revised],'2026-10-03T11:00:00Z');
assert.equal(state.pending['records:hollow'].summary,'The rope has been repaired.','Update describes changed text rather than the opening paragraph');
assert.equal(state.pending['records:hollow'].label,'Updated');
scan(state,'records',[revised],'2026-10-03T12:00:00Z');assert.equal(Object.keys(state.pending).length,1,'Polling does not duplicate updates');
state=JSON.parse(JSON.stringify(state));assert.equal(Object.keys(state.pending).length,1,'Unread changes survive a return visit');
delete state.pending['records:hollow'];scan(state,'records',[revised],'2026-10-03T13:00:00Z');assert.equal(Object.keys(state.pending).length,0,'Reviewed updates remain reviewed');
scan(state,'records',[{...revised,image:'assets/new-hollow.webp'}],'2026-10-04T11:00:00Z');assert.equal(state.pending['records:hollow'].label,'New image');
scan(state,'records',[],'2026-10-04T12:00:00Z');assert.equal(Object.keys(state.pending).length,0,'Unavailable or hidden records leave no stale content');
scan(state,'replies',[],'2026-10-02T11:00:00Z');scan(state,'replies',[{id:'12',title:'About the door',summary:'The GM replied.',sections:['The GM replied.'],route:'#/inbox'}],'2026-10-03T11:00:00Z');assert.equal(state.pending['replies:12'].label,'New');
const other=fresh();scan(other,'records',[one],'2026-10-03T11:00:00Z');assert.equal(Object.keys(other.pending).length,0,'A different character has a separate baseline');
console.log('Catch-up passed: first visit, actual changed text, persistence, acknowledgement, image changes, hidden records and replies.');
